<script setup lang="ts">
import { computed, ref } from 'vue'
import { onPullDownRefresh, onShow } from '@dcloudio/uni-app'
import { cancelMobileInventoryCheck, getMobileInventoryChecks, reviewMobileInventoryCheck, saveMobileInventoryCheck, submitMobileInventoryCheck } from '@/api/business'
import { canPerformMobileAction } from '@/permissions'
import { useContextStore, useSessionStore } from '@/stores'
import type { InventoryCheck, InventoryCheckLine } from '@/types/business'

const session=useSessionStore(),context=useContextStore(),rows=ref<InventoryCheck[]>([]),loading=ref(false),acting=ref(''),message=ref('')
const editingId=ref<number|undefined>(),storeId=ref(''),checkDate=ref(localDate()),note=ref(''),draftLines=ref<InventoryCheckLine[]>([emptyLine()])
const canManage=computed(()=>canPerformMobileAction(session.user,'inventory.manage')),canReview=computed(()=>canPerformMobileAction(session.user,'inventory.review'))
const storeNames=computed(()=>context.stores.map(store=>store.name)),selectedStoreName=computed(()=>context.stores.find(store=>store.id===storeId.value)?.name||storeId.value||'选择盘存门店')
const draftTotal=computed(()=>draftLines.value.reduce((sum,line)=>sum+Number(line.countedQuantity||0)*Number(line.unitPrice||0),0))
onShow(async()=>{if(!context.stores.length&&session.user)await context.load(session.user);storeId.value||=context.currentStoreId||session.user?.boundStoreId||'';await load()});onPullDownRefresh(async()=>{await load();uni.stopPullDownRefresh()})
async function load(){if(loading.value)return;loading.value=true;message.value='';try{rows.value=await getMobileInventoryChecks()}catch(cause){message.value=errorText(cause,'盘存任务加载失败。')}finally{loading.value=false}}
function chooseStore(event:{detail:{value:string|number}}){storeId.value=context.stores[Number(event.detail.value)]?.id||''}
function addLine(){draftLines.value.push(emptyLine())}function removeLine(index:number){if(draftLines.value.length===1){draftLines.value=[emptyLine()];return}draftLines.value.splice(index,1)}
async function save(submitAfter:boolean){if(!canManage.value||acting.value)return;const lines=draftLines.value.map(line=>({...line,itemName:String(line.itemName||'').trim(),itemCode:String(line.itemCode||'').trim(),unit:String(line.unit||'').trim(),packageQuantity:1,unitPrice:Number(line.unitPrice||0),unitPriceEach:Number(line.unitPrice||0),countedQuantity:Number(line.countedQuantity||0),note:String(line.note||'').trim()}));if(!storeId.value||!checkDate.value||lines.some(line=>!line.itemName||!Number.isFinite(line.countedQuantity)||line.countedQuantity<0||!Number.isFinite(line.unitPrice)||line.unitPrice<0)){message.value='请选择门店，并填写有效物品名称、数量和单价。';return}acting.value=editingId.value?String(editingId.value):'create';try{const saved=await saveMobileInventoryCheck({id:editingId.value,storeId:storeId.value,checkDate:checkDate.value,note:note.value.trim(),lines});if(submitAfter)await submitMobileInventoryCheck(saved.id);message.value=submitAfter?'盘存单已提交复核。':'盘存草稿已保存。';resetDraft();await load()}catch(cause){message.value=errorText(cause,'盘存单保存失败。')}finally{acting.value=''}}
function edit(row:InventoryCheck){if(!canManage.value||row.status!=='DRAFT')return;editingId.value=row.id;storeId.value=row.storeId;checkDate.value=row.checkDate;note.value=row.note||'';draftLines.value=row.lines.map(line=>({...line}));message.value='正在编辑盘存草稿。'}
async function submitDraft(row:InventoryCheck){if(!canManage.value||row.status!=='DRAFT'||acting.value)return;acting.value=String(row.id);try{await submitMobileInventoryCheck(row.id);message.value='盘存单已提交复核。';await load()}catch(cause){message.value=errorText(cause,'盘存提交失败。')}finally{acting.value=''}}
async function review(row:InventoryCheck){if(!canReview.value||row.status!=='SUBMITTED'||acting.value||!await confirmAction('确认盘存明细已经核对无误？'))return;acting.value=String(row.id);try{await reviewMobileInventoryCheck(row.id);message.value='盘存单已完成复核。';await load()}catch(cause){message.value=errorText(cause,'盘存复核失败。')}finally{acting.value=''}}
async function cancel(row:InventoryCheck){if(!canManage.value||row.status!=='DRAFT'||acting.value||!await confirmAction('作废后不能恢复，是否继续？'))return;acting.value=String(row.id);try{await cancelMobileInventoryCheck(row.id);message.value='盘存草稿已作废。';if(editingId.value===row.id)resetDraft();await load()}catch(cause){message.value=errorText(cause,'盘存作废失败。')}finally{acting.value=''}}
function resetDraft(){editingId.value=undefined;storeId.value=context.currentStoreId||session.user?.boundStoreId||'';checkDate.value=localDate();note.value='';draftLines.value=[emptyLine()]}
function emptyLine():InventoryCheckLine{return{itemName:'',itemCode:'',unit:'',packageQuantity:1,unitPrice:0,unitPriceEach:0,countedQuantity:0,note:''}}
function localDate(){const now=new Date(),offset=now.getTimezoneOffset()*60000;return new Date(now.getTime()-offset).toISOString().slice(0,10)}
function money(value:unknown){return`¥${Number(value||0).toFixed(2)}`}function statusText(status:string,label?:string){return label||({DRAFT:'草稿',SUBMITTED:'待复核',REVIEWED:'已复核',CANCELLED:'已作废'}as Record<string,string>)[status]||status}
function confirmAction(content:string){return new Promise<boolean>(resolve=>uni.showModal({title:'请确认',content,success:result=>resolve(Boolean(result.confirm)),fail:()=>resolve(false)}))}
function errorText(cause:unknown,fallback:string){const status=Number((cause as{status?:number})?.status||0);return status===403?'当前账号无权操作该门店盘存单。':status===409?'盘存单状态已变化，请刷新后重试。':status===401?'登录已过期，请重新登录。':fallback}
</script>
<template><view class="page"><view class="head"><view><text class="eyebrow">运营现场</text><text class="title">盘存管理</text></view><button :loading="loading" :disabled="loading" @click="load">刷新</button></view><view v-if="message" class="notice">{{message}}</view><view v-if="canManage" class="form"><view class="row"><text class="section-title">{{editingId?'编辑盘存草稿':'新建盘存单'}}</text><button v-if="editingId" class="text-button" @click="resetDraft">取消编辑</button></view><picker :range="storeNames" @change="chooseStore"><view class="input">{{selectedStoreName}}</view></picker><picker mode="date" :value="checkDate" @change="checkDate=String($event.detail.value)"><view class="input">{{checkDate}}</view></picker><view v-for="(line,index) in draftLines" :key="index" class="draft-line"><view class="row"><text class="line-title">明细 {{index+1}}</text><button class="remove" @click="removeLine(index)">删除</button></view><input v-model="line.itemName" class="input" placeholder="物品名称"><view class="line-grid"><input v-model="line.itemCode" class="input" placeholder="物品编码"><input v-model="line.unit" class="input" placeholder="单位"><input v-model="line.countedQuantity" class="input" type="digit" placeholder="盘存数量"><input v-model="line.unitPrice" class="input" type="digit" placeholder="单位价格"></view><input v-model="line.note" class="input" placeholder="明细备注（选填）"></view><button class="add" @click="addLine">添加盘存明细</button><textarea v-model="note" class="input area" placeholder="盘存备注（选填）"></textarea><view class="total">页面合计 <text>{{money(draftTotal)}}</text></view><view class="form-actions"><button @click="save(false)">保存草稿</button><button class="primary" @click="save(true)">保存并提交</button></view></view><text class="section-title records-title">盘存记录</text><view v-if="!rows.length&&!loading" class="state">暂无盘存记录</view><view v-for="row in rows" :key="row.id" class="card"><view class="row"><text class="name">{{row.storeName}} · {{row.checkNo}}</text><text>{{statusText(row.status,row.statusLabel)}}</text></view><text class="copy">{{row.checkDate}} · 盘存金额 {{money(row.totalAmount)}}</text><view class="details"><text v-for="line in row.lines" :key="line.id||`${line.itemName}-${line.itemCode}`">{{line.itemName}}：{{line.countedQuantity}}{{line.unit||''}} · {{money(line.amount)}}</text></view><view class="actions"><button v-if="canManage&&row.status==='DRAFT'" @click="edit(row)">编辑</button><button v-if="canManage&&row.status==='DRAFT'" @click="submitDraft(row)">提交复核</button><button v-if="canManage&&row.status==='DRAFT'" class="danger" @click="cancel(row)">作废</button><button v-if="canReview&&row.status==='SUBMITTED'" @click="review(row)">通过复核</button></view></view></view></template>
<style scoped lang="scss">.page{min-height:100vh;box-sizing:border-box;padding:24rpx;background:#f2f6f5;color:#202124}.head,.row,.actions,.form-actions{display:flex;align-items:center;justify-content:space-between;gap:12rpx}.eyebrow,.title,.section-title,.line-title,.name,.copy,.details text{display:block}.eyebrow,.copy{color:#71807d;font-size:23rpx}.title{margin-top:6rpx;font-size:38rpx;font-weight:750}.head button{margin:0;background:#fff;color:#1f5752}.form,.card,.notice,.state{margin-top:16rpx;padding:24rpx;background:#fff;border:1rpx solid #d9e6e3;border-radius:16rpx}.section-title,.name{font-size:28rpx;font-weight:700}.input{box-sizing:border-box;width:100%;min-height:80rpx;margin-top:12rpx;padding:16rpx;background:#f7faf9;border-radius:12rpx}.area{height:120rpx}.draft-line{margin-top:16rpx;padding:16rpx;border:1rpx solid #d9e6e3;border-radius:14rpx}.line-title{font-size:25rpx;font-weight:680}.remove,.text-button{margin:0;background:transparent;color:#963b30;font-size:23rpx}.line-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10rpx}.add{margin-top:14rpx;background:#e6f3f1;color:#1f5752}.total{margin-top:14rpx;text-align:right;font-size:25rpx}.total text{font-size:31rpx;font-weight:750}.form-actions{margin-top:16rpx}.form-actions button{flex:1;margin:0}.primary{background:#27655f!important;color:#fff}.records-title{margin-top:28rpx}.copy{margin-top:9rpx}.details{margin-top:14rpx;padding-top:12rpx;border-top:1rpx solid #edf0f3}.details text{margin-top:7rpx;color:#4f5661;font-size:23rpx}.actions{margin-top:14rpx;justify-content:flex-start;flex-wrap:wrap}.actions button{margin:0;background:#e6f3f1;color:#1f5752;font-size:23rpx}.actions .danger{background:#fff0ed;color:#963b30}.state,.notice{text-align:center;color:#71807d}</style>
