<script setup lang="ts">
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { createAdminUser, getAdminStores, getAdminUsers, getAuthorizationCatalog, getUserAuthorization, updateAdminUser, updateUserAuthorization, type MobileStore, type MobileUserProfile, type PermissionCatalog, type UserAuthorization } from '@/api/admin'
import type { MobileUserAccount } from '@/types/business'
const roles=['BOSS','FINANCE','STORE_MANAGER','WAREHOUSE','SUPERVISOR','EMPLOYEE']
const roleLabels=['老板','财务','店长','仓库管理员','督导','员工']
const rows=ref<MobileUserAccount[]>([]), stores=ref<MobileStore[]>([]), catalog=ref<PermissionCatalog|null>(null), editing=ref<MobileUserAccount|null>(null), creating=ref(false), form=ref<MobileUserProfile & {username:string;password:string}>({username:'',password:'',displayName:'',role:'EMPLOYEE',storeId:'',storeScope:[],enabled:true}), auth=ref<UserAuthorization>({dataScopes:[],overrides:[]})
const expandedSections=ref({stores:false,scopes:false,permissions:false})
const showPassword=ref(false)
const permissionGroups=computed(()=>{const groups:Record<string,NonNullable<PermissionCatalog>['permissions']>={};for(const item of catalog.value?.permissions||[]){const key=item.moduleCode||'其他权限';(groups[key] ||= []).push(item)}return Object.entries(groups).map(([moduleCode,permissions])=>({moduleCode,permissions}))})
const storeSummary=computed(()=>`${form.value.storeScope.length} 家`)
const scopeSummary=computed(()=>auth.value.dataScopes.length?`${auth.value.dataScopes.length} 项已配置`:'未配置')
const permissionSummary=computed(()=>`${auth.value.overrides.filter(item=>item.effect==='ALLOW').length} 允许 / ${auth.value.overrides.filter(item=>item.effect==='DENY').length} 拒绝`)
onShow(()=>{void refresh()})
async function refresh(){try{[rows.value,stores.value,catalog.value]=await Promise.all([getAdminUsers(),getAdminStores(),getAuthorizationCatalog()])}catch(e){uni.showModal({title:'加载失败',content:'账号权限数据暂时无法加载',showCancel:false})}}
async function edit(row:MobileUserAccount){uni.pageScrollTo({scrollTop:0,duration:180});editing.value=row;creating.value=false;form.value={username:row.username,password:'',displayName:row.displayName,role:row.role,storeId:row.storeId||'',storeScope:row.storeScope||[],enabled:row.enabled};try{auth.value=await getUserAuthorization(row.id)}catch(e){auth.value={dataScopes:[],overrides:[]}}}
function create(){uni.pageScrollTo({scrollTop:0,duration:180});editing.value=null;creating.value=true;auth.value={dataScopes:[],overrides:[]};form.value={username:'',password:'',displayName:'',role:'EMPLOYEE',storeId:'',storeScope:[],enabled:true}}
function chooseRole(e:{detail:{value:number|string}}){form.value.role=roles[Number(e.detail.value)]||form.value.role}
function roleLabel(role:string){return roleLabels[roles.indexOf(role)]||role}
function toggleEnabled(e:any){form.value.enabled=Boolean(e?.detail?.value)}
function hasStore(id:string){return form.value.storeScope.includes(id)}
function toggleStore(id:string){form.value.storeScope=hasStore(id)?form.value.storeScope.filter(item=>item!==id):[...form.value.storeScope,id]}
function override(code:string,e:any){const effect=e?.detail?.value?'ALLOW':'DENY';const next=auth.value.overrides.filter(item=>item.permissionCode!==code);auth.value.overrides=[...next,{permissionCode:code,effect}]}
function permissionEffect(code:string){return auth.value.overrides.find(item=>item.permissionCode===code)?.effect||'继承'}
function choosePermission(code:string,e:{detail:{value:number|string}}){const value=['继承','ALLOW','DENY'][Number(e.detail.value)]||'继承';auth.value.overrides=auth.value.overrides.filter(item=>item.permissionCode!==code);if(value!=='继承')auth.value.overrides.push({permissionCode:code,effect:value as 'ALLOW'|'DENY'})}
function toggleSection(section:'stores'|'scopes'|'permissions'){expandedSections.value[section]=!expandedSections.value[section]}
function chooseScope(domain:string,e:{detail:{value:number|string}}){const mode=catalog.value?.dataScopeModes[Number(e.detail.value)]||'NONE';const existing=auth.value.dataScopes.filter(item=>item.domainCode!==domain);auth.value.dataScopes=[...existing,{domainCode:domain,mode,storeIds:form.value.storeScope,warehouseIds:[]}]}
async function save(){if(!form.value.displayName.trim()||(!editing.value&&( !form.value.username.trim()||!form.value.password))){uni.showToast({title:'请填写完整账号信息',icon:'none'});return}if(form.value.role==='BOSS'){const confirmed=await new Promise<boolean>(resolve=>uni.showModal({title:'高风险操作确认',content:'BOSS 账号拥有全部权限，确定继续保存吗？',success:result=>resolve(result.confirm),fail:()=>resolve(false)}));if(!confirmed)return}try{const wasCreating=creating.value;if(wasCreating){const created=await createAdminUser(form.value);editing.value=created;creating.value=false;auth.value={dataScopes:[],overrides:[]}}else if(editing.value){await updateAdminUser(editing.value.id,{displayName:form.value.displayName,role:form.value.role,storeId:form.value.storeId,storeScope:form.value.storeScope,enabled:form.value.enabled});await updateUserAuthorization(editing.value.id,auth.value)}uni.showToast({title:wasCreating?'账号创建成功，请继续配置权限':'保存成功',icon:'success'});await refresh();if(!wasCreating){editing.value=null;creating.value=false}}catch(e){uni.showModal({title:'保存失败',content:'请检查权限、门店范围和填写内容',showCancel:false})}}
</script>
<template><view class="page"><view class="head"><text class="title">账号权限管理</text><button class="primary" @click="create">新增账号</button></view><view v-if="editing||creating" class="form"><text class="subtitle">基本信息</text><input v-model="form.username" :disabled="Boolean(editing)" placeholder="登录账号"/><view class="password-row"><input v-model="form.password" :password="!showPassword" placeholder="初始密码（新增至少 8 位）"/><button @click="showPassword=!showPassword">{{showPassword?'隐藏':'显示'}}</button></view><input v-model="form.displayName" placeholder="显示名称"/><picker :range="roleLabels" @change="chooseRole"><view class="picker">角色：{{roleLabel(form.role)}}</view></picker><switch :checked="form.enabled" @change="toggleEnabled"/><text class="muted">账号启用</text><view class="section-toggle" @click="toggleSection('stores')"><text>门店范围 · {{storeSummary}}</text><text>{{expandedSections.stores?'收起':'展开'}}</text></view><view v-if="expandedSections.stores" class="checks"><label v-for="store in stores" :key="store.id"><checkbox :checked="hasStore(store.id)" @click="toggleStore(store.id)"/>{{store.name}}</label></view><view class="section-toggle" @click="toggleSection('scopes')"><text>数据范围 · {{scopeSummary}}</text><text>{{expandedSections.scopes?'收起':'展开'}}</text></view><view v-if="expandedSections.scopes"><view v-for="domain in (catalog?.dataScopeDomains||[])" :key="domain" class="scope"><text>{{domain}}</text><picker :range="catalog?.dataScopeModes||[]" @change="chooseScope(domain,$event)"><view class="picker">{{auth.dataScopes.find(item=>item.domainCode===domain)?.mode||'NONE'}}</view></picker></view></view><view class="section-toggle" @click="toggleSection('permissions')"><text>逐项权限 · {{permissionSummary}}</text><text>{{expandedSections.permissions?'收起':'展开'}}</text></view><view v-if="expandedSections.permissions"><view v-for="group in permissionGroups" :key="group.moduleCode"><view v-for="item in group.permissions" :key="item.permissionCode" class="permission"><picker :range="['继承','允许','拒绝']" @change="choosePermission(item.permissionCode,$event)"><view class="permission-choice">{{permissionEffect(item.permissionCode)}}</view></picker><text>{{item.permissionName||item.permissionCode}}</text><text class="muted">{{item.description}}</text></view></view></view><view class="actions"><button @click="editing=null;creating=false">取消</button><button class="primary" @click="save">保存全部权限</button></view></view><view v-for="row in rows" :key="row.id" class="card"><view><text class="name">{{row.displayName}}（{{row.username}}）</text><text class="muted">{{row.roleLabel||row.role}} · {{row.enabled?'已启用':'已停用'}}</text><text class="muted">{{row.effectivePermissionMessage||'权限按角色模板生效'}}</text></view><button @click="edit(row)">编辑权限</button></view></view></template>
<style scoped lang="scss">.page{min-height:100vh;padding:24rpx 24rpx 150rpx;background:#f2f6f5}.head,.card{display:flex;align-items:center;justify-content:space-between;gap:14rpx}.title{font-size:38rpx;font-weight:800}.primary{background:#27655f;color:#fff}.form,.card{margin-top:16rpx;padding:22rpx;background:#fff;border-radius:16rpx}.form input,.picker{margin:12rpx 0;padding:18rpx;background:#f6f8f8;border-radius:10rpx}.name,.muted,.subtitle{display:block}.name{font-size:27rpx;font-weight:700}.muted{margin-top:6rpx;color:#71807d;font-size:22rpx}.subtitle{margin-top:22rpx;font-size:26rpx;font-weight:700}.checks{display:flex;flex-direction:column;gap:12rpx;margin-top:10rpx}.scope,.permission{display:flex;align-items:center;gap:12rpx;margin-top:10rpx;padding:12rpx;background:#f8faf9;border-radius:10rpx}.permission{flex-wrap:wrap}.permission .muted{width:100%}.permission-group{margin-top:12rpx;background:#f8faf9;border-radius:12rpx;overflow:hidden}.group-head{display:flex;justify-content:space-between;padding:18rpx;font-weight:700;color:#27655f}.group-head text:last-child{font-size:22rpx;font-weight:400}.permission-group .permission{margin:0;border-top:1rpx solid #e8efed;border-radius:0}.actions{position:sticky;bottom:0;z-index:10;display:flex;justify-content:flex-end;gap:12rpx;margin:24rpx -22rpx -22rpx;padding:18rpx 22rpx calc(18rpx + env(safe-area-inset-bottom));background:rgba(255,255,255,.96);border-top:1rpx solid #d9e6e3;box-shadow:0 -8rpx 20rpx rgba(37,39,45,.08)}</style>

<style scoped lang="scss">.section-toggle{display:flex;justify-content:space-between;align-items:center;margin-top:16rpx;padding:18rpx;background:#f8faf9;border:1rpx solid #d9e6e3;border-radius:12rpx;color:#27655f;font-weight:700}.section-toggle text:last-child{font-size:22rpx;font-weight:400}</style>
<style scoped lang="scss">.scope .picker,.permission-choice{position:relative;min-width:190rpx;margin:0;padding:14rpx 46rpx 14rpx 16rpx;background:#fff;border:1rpx solid #a9c8c3;border-radius:10rpx;color:#27655f;font-weight:650}.scope .picker::after,.permission-choice::after{content:'⌄';position:absolute;right:14rpx;top:50%;transform:translateY(-52%);font-size:28rpx;color:#27655f}.permission-choice{display:inline-block;min-width:130rpx;text-align:center}</style>
