<script setup lang="ts">
import { ref } from 'vue'; import { onShow } from '@dcloudio/uni-app'; import { createMobileEmployee, createMobileEmployeeAccount, getMobileEmployees, updateMobileEmployee, type MobileEmployee } from '@/api/employees'; import { useSessionStore } from '@/stores'
const session=useSessionStore(),rows=ref<MobileEmployee[]>([]),editing=ref<MobileEmployee|null>(null),form=ref({storeId:'',name:'',phone:'',position:'',employmentType:'FULL_TIME',status:'ACTIVE',hireDate:'',birthday:'',idCardNo:'',remark:''}),statusOptions=['在职','离职','停职'],statusCodes=['ACTIVE','RESIGNED','SUSPENDED']
onShow(()=>{void refresh()});async function refresh(){try{rows.value=await getMobileEmployees()}catch(e){uni.showModal({title:'加载失败',content:'员工档案暂时无法加载',showCancel:false})}}
function edit(row?:MobileEmployee){uni.pageScrollTo({scrollTop:0,duration:180});editing.value=row||null;form.value={storeId:row?.storeId||session.user?.boundStoreId||'',name:row?.name||'',phone:row?.phone||'',position:row?.position||'',employmentType:row?.employmentType||'FULL_TIME',status:row?.status||'ACTIVE',hireDate:row?.hireDate||'',birthday:row?.birthday||'',idCardNo:row?.idCardNo||'',remark:row?.remark||''}}
function chooseStatus(e:{detail:{value:number|string}}){form.value.status=statusCodes[Number(e.detail.value)]||'ACTIVE'}
function statusLabel(v?:string){return ({ACTIVE:'在职',RESIGNED:'离职',SUSPENDED:'停职'} as Record<string,string>)[v||'']||v||'待确认'}
async function save(){if(!form.value.name.trim()||!form.value.storeId){uni.showToast({title:'请填写姓名和所属门店',icon:'none'});return}try{if(editing.value)await updateMobileEmployee(editing.value.id,form.value);else await createMobileEmployee(form.value);uni.showToast({title:'保存成功',icon:'success'});editing.value=null;await refresh()}catch(e){uni.showModal({title:'保存失败',content:'请检查权限和填写内容',showCancel:false})}}
async function createAccount(row:MobileEmployee){try{const result=await createMobileEmployeeAccount(row.id);uni.showModal({title:'账号创建成功',content:`账号：${result.username}\n初始密码：${result.initialPassword}`,showCancel:false})}catch(e){uni.showModal({title:'开号失败',content:'该员工可能已有账号或当前账号无权操作',showCancel:false})}}
</script>
<template><view class="page"><view class="head"><text class="title">员工档案</text><button class="primary" @click="edit()">新增员工</button></view><view v-if="editing!==null" class="form"><text class="subtitle">基本信息</text><input v-model="form.name" placeholder="姓名"/><input v-model="form.storeId" placeholder="所属门店编号"/><input v-model="form.phone" placeholder="手机号"/><input v-model="form.position" placeholder="岗位"/><picker :range="statusOptions" @change="chooseStatus"><view class="select">状态：{{statusLabel(form.status)}}⌄</view></picker><input v-model="form.hireDate" placeholder="入职日期 YYYY-MM-DD"/><input v-model="form.idCardNo" placeholder="身份证号（选填）"/><input v-model="form.remark" placeholder="备注"/><view class="actions"><button @click="editing=null">取消</button><button class="primary" @click="save">保存员工</button></view></view><view v-for="row in rows" :key="row.id" class="card"><view><text class="name">{{row.name}}</text><text class="muted">{{row.storeName||row.storeId}} · {{statusLabel(row.status)}} · {{row.position||'未填写岗位'}}</text><text class="muted">{{row.phone||'未填写手机号'}} · {{row.accountUsername?'账号：'+row.accountUsername:'尚未开号'}}</text></view><view class="card-actions"><button @click="edit(row)">编辑</button><button v-if="!row.accountUsername" @click="createAccount(row)">创建账号</button></view></view><view v-if="!rows.length" class="empty">暂无员工档案</view></view></template>
<style scoped lang="scss">.page{min-height:100vh;padding:24rpx 24rpx 150rpx;background:#f2f6f5}.head,.card,.actions,.card-actions{display:flex;align-items:center;justify-content:space-between;gap:12rpx}.title{font-size:38rpx;font-weight:800}.primary{background:#27655f;color:#fff}.form,.card{margin-top:16rpx;padding:22rpx;background:#fff;border-radius:16rpx}.form input,.select{margin:12rpx 0;padding:18rpx;background:#f6f8f8;border-radius:10rpx}.select{border:1rpx solid #a9c8c3;color:#27655f}.subtitle,.name,.muted{display:block}.subtitle{font-size:27rpx;font-weight:700}.name{font-size:29rpx;font-weight:700}.muted{margin-top:8rpx;color:#71807d;font-size:23rpx}.actions{position:sticky;bottom:0;z-index:10;justify-content:flex-end;margin:18rpx -22rpx -22rpx;padding:18rpx 22rpx calc(18rpx + env(safe-area-inset-bottom));background:rgba(255,255,255,.96);border-top:1rpx solid #d9e6e3}.card-actions{justify-content:flex-end}.empty{text-align:center;padding:50rpx;color:#71807d}</style>
