-- RuGuo recipe catalog verified against 《单杯用量(2).xls》 Sheet3 and the
-- 2026-07-29 supplemental recipe screenshots supplied by the business owner.
-- Business data import, intentionally separate from Flyway schema migrations.
-- Medium/large and 500/1000ml variants are averaged 1:1 into one base recipe.
-- Ice is omitted consistently because it is not an inventory material in this catalog.
-- “加茶至刻度线” quantities are derived after subtracting the listed shaker ingredients.
-- 西瓜大战椰子的 190ml prepared coconut drink is split by the stated 5:1 ratio.
-- Change only the tenant variable when importing the same catalog into another authorized tenant.
set names utf8mb4 collate utf8mb4_unicode_ci;
set @qmai_recipe_tenant_id := 1;
set @qmai_recipe_brand_code := 'ruguo';

start transaction;

drop temporary table if exists tmp_qmai_recipe_import;
create temporary table tmp_qmai_recipe_import (
  product_name varchar(300) not null,
  sort_order int not null,
  material_name varchar(300) not null,
  fruit_name varchar(160) null,
  grams_per_cup decimal(18,3) not null,
  conversion_kind varchar(16) not null,
  conversion_factor decimal(18,6) null
) default charset=utf8mb4 collate=utf8mb4_unicode_ci;

insert into tmp_qmai_recipe_import
  (product_name, sort_order, material_name, fruit_name, grams_per_cup, conversion_kind, conversion_factor)
values
  ('牛油果甘露', 1, '芒果粒', '芒果', 50, 'FLESH', 0.530303),
  ('牛油果甘露', 2, '蒟蒻', null, 40, 'NONE', null),
  ('牛油果甘露', 3, '西柚粒', null, 6.5, 'NONE', null),
  ('牛油果甘露', 4, '牛油果', '牛油果', 90, 'FLESH', 0.78),
  ('牛油果甘露', 5, '椰奶', null, 190, 'NONE', null),
  ('牛油果甘露', 6, '鲜奶', null, 92.5, 'NONE', null),
  ('牛油果甘露', 7, '糖', null, 22.5, 'NONE', null),
  ('牛油果芒果', 1, '芒果肉', '芒果', 90, 'FLESH', 0.530303),
  ('牛油果芒果', 2, '牛油果', '牛油果', 90, 'FLESH', 0.78),
  ('牛油果芒果', 3, '椰奶', null, 175, 'NONE', null),
  ('牛油果芒果', 4, '鲜奶', null, 92.5, 'NONE', null),
  ('牛油果芒果', 5, '糖', null, 22.5, 'NONE', null),
  ('牛油果火龙果', 1, '火龙果肉', '火龙果', 90, 'FLESH', 0.7),
  ('牛油果火龙果', 2, '牛油果', '牛油果', 90, 'FLESH', 0.78),
  ('牛油果火龙果', 3, '椰奶', null, 175, 'NONE', null),
  ('牛油果火龙果', 4, '鲜奶', null, 92.5, 'NONE', null),
  ('牛油果火龙果', 5, '糖', null, 22.5, 'NONE', null),
  ('牛油果追凤梨', 1, '凤梨果肉', '凤梨', 70, 'FLESH', 0.598264),
  ('牛油果追凤梨', 2, '牛油果', '牛油果', 80, 'FLESH', 0.78),
  ('牛油果追凤梨', 3, '椰奶', null, 150, 'NONE', null),
  ('牛油果追凤梨', 4, '鲜奶', null, 85, 'NONE', null),
  ('牛油果追凤梨', 5, '糖', null, 25, 'NONE', null),
  ('羽衣甘蓝牛油果', 1, '爆爆珠', null, 50, 'NONE', null),
  ('羽衣甘蓝牛油果', 2, '奇亚籽', null, 25, 'NONE', null),
  ('羽衣甘蓝牛油果', 3, '酸奶', null, 60, 'NONE', null),
  ('羽衣甘蓝牛油果', 4, '牛油果', '牛油果', 60, 'FLESH', 0.78),
  ('羽衣甘蓝牛油果', 5, '鲜奶', null, 60, 'NONE', null),
  ('羽衣甘蓝牛油果', 6, '椰奶', null, 60, 'NONE', null),
  ('羽衣甘蓝牛油果', 7, '淡奶油', null, 15, 'NONE', null),
  ('羽衣甘蓝牛油果', 8, '糖', null, 25, 'NONE', null),
  ('羽衣甘蓝牛油果', 9, '羽衣甘蓝', '羽衣甘蓝', 7, 'ONE', null),
  ('牛油果追桃桃', 1, '腌制水蜜桃', '桃子', 90, 'FLESH', 0.742268),
  ('牛油果追桃桃', 2, '牛油果', '牛油果', 90, 'FLESH', 0.78),
  ('牛油果追桃桃', 3, '椰奶', null, 175, 'NONE', null),
  ('牛油果追桃桃', 4, '鲜奶', null, 92.5, 'NONE', null),
  ('牛油果追桃桃', 5, '糖', null, 22.5, 'NONE', null),
  ('黄皮仙桃', 1, '水蜜桃', '桃子', 220, 'FLESH', 0.742268),
  ('黄皮仙桃', 2, '黄皮汁', '黄皮', 40, 'ONE', null),
  ('黄皮仙桃', 3, '茶', null, 260, 'NONE', null),
  ('黄皮仙桃', 4, '糖', null, 50, 'NONE', null),
  ('黄皮仙桃', 5, '蒟蒻', null, 40, 'NONE', null),
  ('暴打黄皮冰柠茶', 1, '黄皮肉', '黄皮', 150, 'FLESH', 0.740408),
  ('暴打黄皮冰柠茶', 2, '柠檬角', '柠檬', 15, 'FLESH', 0.9),
  ('暴打黄皮冰柠茶', 3, '茶', null, 260, 'NONE', null),
  ('暴打黄皮冰柠茶', 4, '糖', null, 60, 'NONE', null),
  ('黄皮冰茶乳酸菌', 1, '黄皮肉', '黄皮', 150, 'FLESH', 0.740408),
  ('黄皮冰茶乳酸菌', 2, '柠檬角', '柠檬', 15, 'FLESH', 0.9),
  ('黄皮冰茶乳酸菌', 3, '乳酸菌', null, 40, 'NONE', null),
  ('黄皮冰茶乳酸菌', 4, '糖', null, 60, 'NONE', null),
  ('芝芝葡萄', 1, '葡萄肉', '葡萄', 130, 'FLESH', 0.65),
  ('芝芝葡萄', 2, '葡萄汁', '葡萄', 130, 'ONE', null),
  ('芝芝葡萄', 3, '茶', null, 50, 'NONE', null),
  ('芝芝葡萄', 4, '糖', null, 45, 'NONE', null),
  ('芝芝葡萄', 5, '奶盖', null, 50, 'NONE', null),
  ('多肉葡萄冰冰茶', 1, '葡萄肉', '葡萄', 130, 'FLESH', 0.65),
  ('多肉葡萄冰冰茶', 2, '葡萄汁', '葡萄', 130, 'ONE', null),
  ('多肉葡萄冰冰茶', 3, '茶', null, 50, 'NONE', null),
  ('多肉葡萄冰冰茶', 4, '糖', null, 45, 'NONE', null),
  ('多肉葡萄冰冰茶', 5, '蒟蒻', null, 40, 'NONE', null),
  ('桃桃葡萄冰', 1, '桃子果肉', '桃子', 130, 'FLESH', 0.742268),
  ('桃桃葡萄冰', 2, '葡萄汁', '葡萄', 130, 'ONE', null),
  ('桃桃葡萄冰', 3, '茶', null, 50, 'NONE', null),
  ('桃桃葡萄冰', 4, '糖', null, 35, 'NONE', null),
  ('桃桃葡萄冰', 5, '蒟蒻', null, 40, 'NONE', null),
  ('凤梨葡萄冰', 1, '凤梨块', '凤梨', 130, 'FLESH', 0.598264),
  ('凤梨葡萄冰', 2, '葡萄汁', '葡萄', 130, 'ONE', null),
  ('凤梨葡萄冰', 3, '茶', null, 50, 'NONE', null),
  ('凤梨葡萄冰', 4, '糖', null, 40, 'NONE', null),
  ('凤梨葡萄冰', 5, '蒟蒻', null, 40, 'NONE', null),
  ('霸气葡萄水果茶', 1, '葡萄肉', '葡萄', 170, 'FLESH', 0.65),
  ('霸气葡萄水果茶', 2, '葡萄汁', '葡萄', 130, 'ONE', null),
  ('霸气葡萄水果茶', 3, '茶', null, 225, 'NONE', null),
  ('霸气葡萄水果茶', 4, '糖', null, 40, 'NONE', null),
  ('霸气葡萄水果茶', 5, '蒟蒻', null, 40, 'NONE', null),
  ('霸气葡萄水果茶', 6, '柠檬角', '柠檬', 15, 'FLESH', 0.9),
  ('杨梅与凤梨', 1, '杨梅果肉', '杨梅', 170, 'FLESH', 0.8),
  ('杨梅与凤梨', 2, '凤梨汁', '凤梨', 80, 'JUICE', 1.3372),
  ('杨梅与凤梨', 3, '茶', null, 340, 'NONE', null),
  ('杨梅与凤梨', 4, '糖', null, 25, 'NONE', null),
  ('满杯杨梅冰冰茶', 1, '杨梅果肉', '杨梅', 180, 'FLESH', 0.8),
  ('满杯杨梅冰冰茶', 2, '茶', null, 80, 'NONE', null),
  ('满杯杨梅冰冰茶', 3, '糖', null, 30, 'NONE', null),
  ('芝士杨梅冰', 1, '杨梅果肉', '杨梅', 190, 'FLESH', 0.8),
  ('芝士杨梅冰', 2, '茶', null, 80, 'NONE', null),
  ('芝士杨梅冰', 3, '糖', null, 30, 'NONE', null),
  ('芝士杨梅冰', 4, '奶盖', null, 50, 'NONE', null),
  ('胭脂粉芭乐', 1, '腌制芭乐', '芭乐', 220, 'FLESH', 0.735676),
  ('胭脂粉芭乐', 2, '柠檬角', '柠檬', 15, 'FLESH', 0.9),
  ('胭脂粉芭乐', 3, '糖', null, 30, 'NONE', null),
  ('胭脂粉芭乐', 4, '茶', null, 360, 'NONE', null),
  ('芭乐桃桃', 1, '腌制芭乐', '芭乐', 120, 'FLESH', 0.735676),
  ('芭乐桃桃', 2, '腌制水蜜桃', '桃子', 120, 'FLESH', 0.742268),
  ('芭乐桃桃', 3, '糖', null, 30, 'NONE', null),
  ('芭乐桃桃', 4, '茶', null, 310, 'NONE', null),
  ('芭乐桃桃', 5, '蒟蒻', null, 40, 'NONE', null),
  ('满杯桃桃冰冰茶', 1, '腌制水蜜桃', '桃子', 260, 'FLESH', 0.742268),
  ('满杯桃桃冰冰茶', 2, '糖', null, 25, 'NONE', null),
  ('满杯桃桃冰冰茶', 3, '茶', null, 70, 'NONE', null),
  ('满杯桃桃冰冰茶', 4, '蒟蒻', null, 40, 'NONE', null),
  ('芝士桃桃冰', 1, '腌制水蜜桃', '桃子', 260, 'FLESH', 0.742268),
  ('芝士桃桃冰', 2, '糖', null, 25, 'NONE', null),
  ('芝士桃桃冰', 3, '茶', null, 70, 'NONE', null),
  ('芝士桃桃冰', 4, '奶盖', null, 50, 'NONE', null),
  ('霸气桃桃水果茶', 1, '腌制水蜜桃', '桃子', 250, 'FLESH', 0.742268),
  ('霸气桃桃水果茶', 2, '糖', null, 30, 'NONE', null),
  ('霸气桃桃水果茶', 3, '茶', null, 300, 'NONE', null),
  ('霸气桃桃水果茶', 4, '蒟蒻', null, 40, 'NONE', null),
  ('大颗芒果冰茶', 1, '芒果', '芒果', 300, 'FLESH', 0.530303),
  ('大颗芒果冰茶', 2, '茶', null, 150, 'NONE', null),
  ('大颗芒果冰茶', 3, '糖', null, 15, 'NONE', null),
  ('生椰芒芒冰茶', 1, '芒果', '芒果', 300, 'FLESH', 0.530303),
  ('生椰芒芒冰茶', 2, '生椰乳', null, 150, 'NONE', null),
  ('超多芒芒酸奶冰', 1, '酸奶', null, 70, 'NONE', null),
  ('超多芒芒酸奶冰', 2, '芒果条', '芒果', 150, 'FLESH', 0.530303),
  ('超多芒芒酸奶冰', 3, '椰奶', null, 90, 'NONE', null),
  ('超多芒芒酸奶冰', 4, '糖', null, 25, 'NONE', null),
  ('久抹', 1, '鲜牛乳', null, 240, 'NONE', null),
  ('久抹', 2, '爱护奶', null, 30, 'NONE', null),
  ('久抹', 3, '糖', null, 20, 'NONE', null),
  ('久抹', 4, '抹茶液', null, 60, 'NONE', null),
  ('芒也', 1, '芒果粒', '芒果', 50, 'FLESH', 0.530303),
  ('芒也', 2, '生椰乳', null, 160, 'NONE', null),
  ('芒也', 3, '鲜牛乳', null, 70, 'NONE', null),
  ('芒也', 4, '爱护奶', null, 10, 'NONE', null),
  ('芒也', 5, '糖', null, 5, 'NONE', null),
  ('芒也', 6, '抹茶液', null, 60, 'NONE', null),
  ('夏日菠萝冰', 1, '凤梨果肉', '凤梨', 160, 'FLESH', 0.598264),
  ('夏日菠萝冰', 2, '凤梨汁', '凤梨', 50, 'JUICE', 1.3372),
  ('夏日菠萝冰', 3, '茶', null, 60, 'NONE', null),
  ('夏日菠萝冰', 4, '糖', null, 33, 'NONE', null),
  ('爆汁西瓜桃桃冰', 1, '腌制水蜜桃', '桃子', 100, 'FLESH', 0.742268),
  ('爆汁西瓜桃桃冰', 2, '西瓜', '西瓜', 170, 'FLESH', 0.8),
  ('爆汁西瓜桃桃冰', 3, '茶', null, 40, 'NONE', null),
  ('爆汁西瓜桃桃冰', 4, '糖', null, 25, 'NONE', null),
  ('夏日西瓜雪梨冰', 1, '西瓜', '西瓜', 380, 'FLESH', 0.8),
  ('夏日西瓜雪梨冰', 2, '雪梨汁', '雪梨', 75, 'JUICE', 1.265),
  ('夏日西瓜雪梨冰', 3, '糖', null, 10, 'NONE', null),
  ('每日阳光甜橙冰', 1, '橙子肉', '橙子', 65, 'FLESH', 0.54),
  ('每日阳光甜橙冰', 2, '橙子块', '橙子', 132.5, 'FLESH', 0.54),
  ('每日阳光甜橙冰', 3, '橙子汁', '橙子', 132.5, 'JUICE', 1.562),
  ('每日阳光甜橙冰', 4, '雪梨汁', '雪梨', 90, 'JUICE', 1.265),
  ('每日阳光甜橙冰', 5, '糖', null, 35, 'NONE', null),
  ('芒芒甘露', 1, '芒果粒', '芒果', 50, 'FLESH', 0.530303),
  ('芒芒甘露', 2, '蒟蒻', null, 50, 'NONE', null),
  ('芒芒甘露', 3, '西柚粒', null, 5, 'NONE', null),
  ('芒芒甘露', 4, '茶冻', null, 70, 'NONE', null),
  ('芒芒甘露', 5, '糖', null, 5, 'NONE', null),
  ('芒芒甘露', 6, '芒果汁', '芒果', 235, 'JUICE', 1.8867),
  ('芒芒甘露', 7, '椰奶', null, 235, 'NONE', null),
  ('霸气橙子', 1, '橙子角', '橙子', 120, 'FLESH', 0.54),
  ('霸气橙子', 2, '柠檬角', '柠檬', 10, 'FLESH', 0.9),
  ('霸气橙子', 3, '橙子汁', '橙子', 130, 'JUICE', 1.562),
  ('霸气橙子', 4, '糖', null, 30, 'NONE', null),
  ('霸气橙子', 5, '茶', null, 310, 'NONE', null),
  ('芒芒凤梨', 1, '芒果肉', '芒果', 150, 'FLESH', 0.530303),
  ('芒芒凤梨', 2, '凤梨汁', '凤梨', 100, 'JUICE', 1.3372),
  ('芒芒凤梨', 3, '柠檬角', '柠檬', 10, 'FLESH', 0.9),
  ('芒芒凤梨', 4, '糖', null, 25, 'NONE', null),
  ('芒芒凤梨', 5, '茶', null, 310, 'NONE', null),
  ('满杯VC水果茶', 1, '芒果', '芒果', 75, 'FLESH', 0.530303),
  ('满杯VC水果茶', 2, '西瓜', '西瓜', 80, 'FLESH', 0.8),
  ('满杯VC水果茶', 3, '橙子角', '橙子', 60, 'FLESH', 0.54),
  ('满杯VC水果茶', 4, '柠檬角', '柠檬', 10, 'FLESH', 0.9),
  ('满杯VC水果茶', 5, '小金橘', '金桔', 10, 'ONE', null),
  ('满杯VC水果茶', 6, '橙子汁', '橙子', 80, 'JUICE', 1.562),
  ('满杯VC水果茶', 7, '百香果', '百香果', 15, 'ONE', null),
  ('满杯VC水果茶', 8, '糖', null, 40, 'NONE', null),
  ('满杯VC水果茶', 9, '茶', null, 300, 'NONE', null),
  ('凤梨百香火龙果', 1, '火龙果肉', '火龙果', 140, 'FLESH', 0.7),
  ('凤梨百香火龙果', 2, '凤梨汁', '凤梨', 100, 'JUICE', 1.3372),
  ('凤梨百香火龙果', 3, '柠檬角', '柠檬', 10, 'FLESH', 0.9),
  ('凤梨百香火龙果', 4, '百香果', '百香果', 30, 'ONE', null),
  ('凤梨百香火龙果', 5, '糖', null, 30, 'NONE', null),
  ('凤梨百香火龙果', 6, '茶', null, 300, 'NONE', null),
  ('百香芒芒金凤梨', 1, '芒果肉', '芒果', 150, 'FLESH', 0.530303),
  ('百香芒芒金凤梨', 2, '凤梨汁', '凤梨', 80, 'JUICE', 1.3372),
  ('百香芒芒金凤梨', 3, '百香果', '百香果', 30, 'ONE', null),
  ('百香芒芒金凤梨', 4, '柠檬角', '柠檬', 10, 'FLESH', 0.9),
  ('百香芒芒金凤梨', 5, '糖', null, 30, 'NONE', null),
  ('百香芒芒金凤梨', 6, '茶', null, 350, 'NONE', null),
  ('茉香芝士芒芒', 1, '芒果肉', '芒果', 180, 'FLESH', 0.530303),
  ('茉香芝士芒芒', 2, '糖', null, 35, 'NONE', null),
  ('茉香芝士芒芒', 3, '茶', null, 350, 'NONE', null),
  ('茉香芝士芒芒', 4, '奶盖', null, 50, 'NONE', null),
  ('芝士火龙果', 1, '火龙果肉', '火龙果', 180, 'FLESH', 0.7),
  ('芝士火龙果', 2, '糖', null, 40, 'NONE', null),
  ('芝士火龙果', 3, '茶', null, 350, 'NONE', null),
  ('芝士火龙果', 4, '奶盖', null, 50, 'NONE', null),
  ('榴莲和芒果', 1, '榴莲肉', '榴莲', 50, 'ONE', null),
  ('榴莲和芒果', 2, '芒果粒', '芒果', 50, 'FLESH', 0.530303),
  ('榴莲和芒果', 3, '芒果汁', '芒果', 195, 'JUICE', 1.8867),
  ('榴莲和芒果', 4, '椰奶', null, 195, 'NONE', null),
  ('榴莲和芒果', 5, '糖', null, 5, 'NONE', null),
  ('黄金榴莲牛油果', 1, '榴莲肉', '榴莲', 50, 'ONE', null),
  ('黄金榴莲牛油果', 2, '牛油果', '牛油果', 80, 'FLESH', 0.78),
  ('黄金榴莲牛油果', 3, '椰奶', null, 150, 'NONE', null),
  ('黄金榴莲牛油果', 4, '鲜奶', null, 85, 'NONE', null),
  ('黄金榴莲牛油果', 5, '糖', null, 15, 'NONE', null),
  ('手打柠檬茶', 1, '柠檬', '柠檬', 80, 'FLESH', 0.9),
  ('手打柠檬茶', 2, '茶冻', null, 70, 'NONE', null),
  ('手打柠檬茶', 3, '糖', null, 60, 'NONE', null),
  ('手打柠檬茶', 4, '茶', null, 280, 'NONE', null),
  ('超绿轻体瓶', 1, '雪梨', '雪梨', 250, 'FLESH', 0.788623),
  ('超绿轻体瓶', 2, '橙子', '橙子', 120, 'FLESH', 0.54),
  ('超绿轻体瓶', 3, '羽衣甘蓝', '羽衣甘蓝', 20, 'ONE', null),
  ('超绿轻体瓶', 4, '柠檬果肉', '柠檬', 15, 'FLESH', 0.9),
  ('元气小红瓶', 1, '火龙果', '火龙果', 50, 'FLESH', 0.7),
  ('元气小红瓶', 2, '凤梨', '凤梨', 70, 'FLESH', 0.598264),
  ('元气小红瓶', 3, '橙子', '橙子', 70, 'FLESH', 0.54),
  ('元气小红瓶', 4, '苹果', '苹果', 70, 'FLESH', 0.897855),
  ('元气小红瓶', 5, '雪梨', '雪梨', 150, 'FLESH', 0.788623),
  ('元气小红瓶', 6, '柠檬皮', '柠檬', 5, 'FLESH', 0.9),
  ('乘风破浪阳光橙', 1, '橙子', '橙子', 280, 'FLESH', 0.54),
  ('乘风破浪阳光橙', 2, '雪梨', '雪梨', 170, 'FLESH', 0.788623),
  ('玫珑蜜瓜冰', 1, '玫珑瓜果肉', '玫珑瓜', 210, 'ONE', null),
  ('玫珑蜜瓜冰', 2, '茶', null, 60, 'NONE', null),
  ('玫珑蜜瓜冰', 3, '糖', null, 30, 'NONE', null),
  ('西瓜大战椰子', 1, '西瓜果肉', '西瓜', 200, 'FLESH', 0.8),
  ('西瓜大战椰子', 2, '生椰乳', null, 158.333, 'NONE', null),
  ('西瓜大战椰子', 3, '水', null, 31.667, 'NONE', null),
  ('生椰龙眼冰', 1, '龙眼果肉', '龙眼', 160, 'ONE', null),
  ('生椰龙眼冰', 2, '蒟蒻/爆爆珠', null, 50, 'NONE', null),
  ('生椰龙眼冰', 3, '生椰乳', null, 100, 'NONE', null),
  ('青柠百香果', 1, '蒟蒻', null, 25, 'NONE', null),
  ('青柠百香果', 2, '茶冻', null, 70, 'NONE', null),
  ('青柠百香果', 3, '柠檬角', '柠檬', 40, 'FLESH', 0.9),
  ('青柠百香果', 4, '百香果', '百香果', 30, 'ONE', null),
  ('青柠百香果', 5, '小金橘', '金桔', 10, 'ONE', null),
  ('青柠百香果', 6, '糖', null, 70, 'NONE', null),
  ('青柠百香果', 7, '茶', null, 200, 'NONE', null),
  ('芝芝玫珑瓜', 1, '玫珑瓜果肉', '玫珑瓜', 210, 'ONE', null),
  ('芝芝玫珑瓜', 2, '茶', null, 60, 'NONE', null),
  ('芝芝玫珑瓜', 3, '糖', null, 30, 'NONE', null),
  ('芝芝玫珑瓜', 4, '奶盖', null, 50, 'NONE', null),
  ('羽衣甘蓝柠檬茶', 1, '茶冻', null, 70, 'NONE', null),
  ('羽衣甘蓝柠檬茶', 2, '柠檬角', '柠檬', 80, 'FLESH', 0.9),
  ('羽衣甘蓝柠檬茶', 3, '羽衣甘蓝汁', '羽衣甘蓝', 25, 'JUICE', 1),
  ('羽衣甘蓝柠檬茶', 4, '糖', null, 60, 'NONE', null),
  ('羽衣甘蓝柠檬茶', 5, '茶', null, 235, 'NONE', null),
  ('丹青', 1, '茉莉绿茶', null, 250, 'NONE', null),
  ('丹青', 2, '爱护奶', null, 20, 'NONE', null),
  ('丹青', 3, '牛奶', null, 90, 'NONE', null),
  ('丹青', 4, '糖', null, 35, 'NONE', null),
  ('芳华', 1, '蜜桃乌龙茶', null, 250, 'NONE', null),
  ('芳华', 2, '爱护奶', null, 20, 'NONE', null),
  ('芳华', 3, '牛奶', null, 90, 'NONE', null),
  ('芳华', 4, '糖', null, 35, 'NONE', null),
  ('青岚', 1, '鲜牛乳', null, 240, 'NONE', null),
  ('青岚', 2, '爱护奶', null, 30, 'NONE', null),
  ('青岚', 3, '糖', null, 20, 'NONE', null),
  ('青岚', 4, '奶盖', null, 50, 'NONE', null),
  ('青岚', 5, '抹茶液', null, 60, 'NONE', null),
  ('满杯百香果', 1, '蒟蒻', null, 25, 'NONE', null),
  ('满杯百香果', 2, '茶冻', null, 70, 'NONE', null),
  ('满杯百香果', 3, '百香果', '百香果', 60, 'ONE', null),
  ('满杯百香果', 4, '糖', null, 70, 'NONE', null),
  ('满杯百香果', 5, '茶', null, 220, 'NONE', null),
  ('阳光小青提', 1, '带皮青提', '青提', 100, 'ONE', null),
  ('阳光小青提', 2, '雪梨', '雪梨', 200, 'FLESH', 0.788623),
  ('阳光小青提', 3, '凤梨', '凤梨', 70, 'FLESH', 0.598264),
  ('阳光小青提', 4, '苹果', '苹果', 50, 'FLESH', 0.897855),
  ('阳光小青提', 5, '柠檬皮', '柠檬', 5, 'FLESH', 0.9);

update qmai_recipe_definition
set active = 0,
    version_no = version_no + 1,
    updated_by_name = '系统导入（单杯用量表+补充配方截图）'
where tenant_id = @qmai_recipe_tenant_id
  and brand_code = @qmai_recipe_brand_code
  and active = 1;

insert into qmai_recipe_definition
  (tenant_id, brand_code, product_name, active, version_no, updated_by_name)
select distinct @qmai_recipe_tenant_id, @qmai_recipe_brand_code, product_name, 1, 1,
  '系统导入（单杯用量表+补充配方截图）'
from tmp_qmai_recipe_import
on duplicate key update
  active = 1,
  version_no = qmai_recipe_definition.version_no + 1,
  updated_by_name = '系统导入（单杯用量表+补充配方截图）';

delete ingredient
from qmai_recipe_ingredient ingredient
join qmai_recipe_definition definition on definition.id = ingredient.recipe_id
join (select distinct product_name from tmp_qmai_recipe_import) imported
  on imported.product_name = definition.product_name
where definition.tenant_id = @qmai_recipe_tenant_id
  and definition.brand_code = @qmai_recipe_brand_code;

insert into qmai_recipe_ingredient
  (recipe_id, material_name, fruit_name, grams_per_cup, conversion_kind, conversion_factor, sort_order)
select definition.id, imported.material_name, imported.fruit_name, imported.grams_per_cup,
       imported.conversion_kind, imported.conversion_factor, imported.sort_order
from tmp_qmai_recipe_import imported
join qmai_recipe_definition definition
  on definition.tenant_id = @qmai_recipe_tenant_id
 and definition.brand_code = @qmai_recipe_brand_code
 and definition.product_name = imported.product_name
order by imported.product_name, imported.sort_order;

drop temporary table tmp_qmai_recipe_import;
commit;
