<script setup lang="ts">
import { computed, ref } from 'vue'
import { onLoad, onPullDownRefresh } from '@dcloudio/uni-app'
import { adjustMobileInspectionDetection, getMobileInspectionEvidence, getMobileInspectionRecord, revokeMobileInspectionDetection } from '@/api/business'
import ProtectedAttachmentList, { type ProtectedAttachment } from '@/components/ProtectedAttachmentList.vue'
import StatusTimeline, { type TimelineItem } from '@/components/StatusTimeline.vue'
import { useSessionStore } from '@/stores'
import type { InspectionEvidenceCandidates, InspectionItemResult, InspectionRecord } from '@/types/business'

interface DetectionDecision { key:string;attachmentId?:number;fileName:string;status:string;revision:number;clauseId?:number;clauseTitle?:string;summary?:string;deduction?:number;manualReason?:string }
const session=useSessionStore(),recordId=ref(''),record=ref<InspectionRecord|null>(null),evidence=ref<InspectionEvidenceCandidates|null>(null),loading=ref(false),message=ref(''),acting=ref(''),clauseSelections=ref<Record<string,number>>({})
const canRead=computed(()=>session.hasPermission('inspection.read')),canManage=computed(()=>session.hasPermission('inspection.manage')),canReadAttachments=computed(()=>session.hasPermission('attachment.read'))
const clauses=computed(()=>record.value?.itemResults||[]),decisions=computed(()=>parseDecisions(record.value?.photosJson))
const attachments=computed<ProtectedAttachment[]>(()=>canReadAttachments.value?(evidence.value?.candidates||[]).filter(item=>item.attachmentId&&['LINKED','UNLINKED'].includes(item.status)).map(item=>({id:item.attachmentId!,fileName:item.fileName||`现场照片-${Number(item.photoIndex||0)+1}`,contentType:item.contentType,path:`/api/storage/attachments/${item.attachmentId}`})):[])
onLoad(query=>{recordId.value=String(query?.id||'');void load()});onPullDownRefresh(async()=>{await load();uni.stopPullDownRefresh()})
async function load(){if(!recordId.value||!canRead.value||loading.value)return;loading.value=true;message.value='';try{record.value=await getMobileInspectionRecord(recordId.value);if(canManage.value){try{evidence.value=await getMobileInspectionEvidence(recordId.value)}catch(cause){message.value=friendlyError(cause,'历史证据元数据暂时无法加载。')}}initializeSelections()}catch(cause){message.value=friendlyError(cause,'巡检详情暂时无法加载。')}finally{loading.value=false}}
function initializeSelections(){for(const decision of decisions.value){const index=Math.max(0,clauses.value.findIndex(item=>item.standardItemId===decision.clauseId));clauseSelections.value[decision.key]=index}}
async function revoke(decision:DetectionDecision){if(!canManage.value||!decision.key||acting.value)return;if(!await confirmAction('撤销后服务端会恢复该条款的原始状态，是否继续？'))return;acting.value=decision.key;try{const result=await revokeMobileInspectionDetection(recordId.value,decision.key,decision.revision);record.value=result.record;message.value=result.changed?'识别结论已撤销，条款分数已由服务端重算。':'该识别结论已经是撤销状态。';initializeSelections()}catch(cause){message.value=friendlyError(cause,'识别结论撤销失败，请刷新后重试。')}finally{acting.value=''}}
async function adjust(decision:DetectionDecision){if(!canManage.value||!decision.key||acting.value)return;const clause=clauses.value[clauseSelections.value[decision.key]||0];if(!clause){message.value='请选择需要关联的历史巡检条款。';return}const reason=await askReason();if(!reason)return;acting.value=decision.key;try{const result=await adjustMobileInspectionDetection(recordId.value,decision.key,clause.standardItemId,reason);record.value=result.record;message.value=result.changed?'人工条款调整已保存，扣分和总分已由服务端重算。':'识别结论没有发生变化。';initializeSelections()}catch(cause){message.value=friendlyError(cause,'人工调整失败，请刷新后重试。')}finally{acting.value=''}}
function parseDecisions(value?:string):DetectionDecision[]{if(!value)return[];try{const parsed=JSON.parse(value);if(!Array.isArray(parsed))return[];return parsed.map((photo,index)=>{const node=photo&&typeof photo.detection==='object'?photo.detection:photo;return{key:String(node?.detectionKey||node?.detection_key||''),attachmentId:Number(node?.attachmentId||photo?.attachmentId||0)||undefined,fileName:String(photo?.fileName||node?.filename||`现场照片-${index+1}`),status:String(node?.decisionStatus||node?.decision_status||photo?.reviewStatus||photo?.review_status||'PENDING').toUpperCase(),revision:Number(node?.revision||0),clauseId:Number(node?.clauseId||node?.clause_id||0)||undefined,clauseTitle:String(node?.clauseTitle||node?.clause_title||''),summary:String(node?.detection_summary||node?.detectionSummary||node?.suggested_issue||''),deduction:Number(node?.confirmedDeduction??node?.finalDeduction??node?.suggestedDeduction??0),manualReason:String(node?.manualAdjustmentReason||'')}})}catch{return[]}}
function decisionTimeline(decision:DetectionDecision):TimelineItem[]{return[{label:'AI 识别建议已生成',done:true},{label:decision.manualReason?`人工调整条款：${decision.manualReason}`:'未进行人工条款调整',done:Boolean(decision.manualReason)},{label:decision.status==='CONFIRMED'?'人工确认并应用扣分':decision.status==='REVOKED'?'人工结论已撤销':'等待人工确认',done:['CONFIRMED','REVOKED'].includes(decision.status)},{label:`当前决策版本 ${decision.revision}`,done:true}]}
function statusText(status:string){return({CONFIRMED:'已人工确认',REVOKED:'已撤销',PENDING:'待人工确认',UNMATCHED:'未匹配条款',ACCEPTED:'已人工确认',DISMISSED:'已人工处理'}as Record<string,string>)[status]||status}
function evidenceStatus(status:string){return({LINKED:'已关联条款',UNLINKED:'原图待关联',ORIGINAL_NOT_STORED:'原图未入库',INVALID_TYPE:'附件类型不可用'}as Record<string,string>)[status]||status}
function clauseLabel(item?:InspectionItemResult){return item?.title||item?.code||(item?`条款 ${item.standardItemId}`:'暂无可选条款')}
function chooseClause(decision:DetectionDecision,event:{detail:{value:string|number}}){clauseSelections.value[decision.key]=Number(event.detail.value)}
function confirmAction(content:string){return new Promise<boolean>(resolve=>uni.showModal({title:'撤销识别结论',content,confirmText:'确认撤销',success:result=>resolve(Boolean(result.confirm)),fail:()=>resolve(false)}))}
function askReason(){return new Promise<string>(resolve=>uni.showModal({title:'人工调整原因',editable:true,placeholderText:'请填写调整依据',success:result=>resolve(result.confirm?String(result.content||'').trim():''),fail:()=>resolve('')}))}
function friendlyError(cause:unknown,fallback:string){const status=Number((cause as{status?:number})?.status||0),code=String((cause as{code?:string})?.code||'');if(status===403)return'当前账号无权查看或处理该巡检证据。';if(status===401)return'登录已过期，请重新登录。';if(status===409||code==='INSPECTION_DETECTION_CONFLICT')return'识别结论已被其他人处理，请刷新后重试。';return fallback}
</script>
<template><view class="page"><view v-if="message" class="notice">{{message}}</view><view v-if="!record&&!loading" class="state">巡检记录不存在或当前账号无权查看。</view><template v-if="record"><view class="header"><view><text class="eyebrow">{{record.storeName||record.storeId}} · {{record.inspectionDate}}</text><text class="title">巡检证据详情</text><text class="copy">{{record.inspector||'巡检人员'}} · 标准 {{record.standardVersion||'—'}}</text></view><text class="score">{{record.displayScore??record.score}} 分</text></view><view class="section"><text class="section-title">历史现场证据</text><ProtectedAttachmentList :items="attachments" @error="message=$event"/><view v-for="item in evidence?.candidates||[]" :key="`${item.photoIndex}-${item.attachmentId}`" class="evidence-row"><text>{{item.fileName||`现场照片-${Number(item.photoIndex||0)+1}`}}</text><text>{{evidenceStatus(item.status)}} · {{item.linkedClauseIds.length}} 条款</text></view><text v-if="!evidence?.candidates.length" class="copy empty">暂无可读取的历史现场证据</text></view><view class="section"><text class="section-title">条款结论</text><view v-for="item in clauses" :key="item.snapshotId||item.standardItemId" class="clause"><view class="row"><text class="name">{{clauseLabel(item)}}</text><text>{{item.actualScore}} / {{item.standardScore??'—'}}</text></view><text class="copy">{{item.deductionReason||'无扣分说明'}} · {{item.rectificationStatus||'无需整改'}}</text></view></view><view class="section"><text class="section-title">AI 与人工结论轨迹</text><text v-if="!decisions.length" class="copy empty">该记录没有可操作的 AI 识别结论</text><view v-for="decision in decisions" :key="decision.key||decision.fileName" class="decision"><view class="row"><view><text class="name">{{decision.fileName}}</text><text class="copy">{{decision.clauseTitle||'未匹配正式条款'}} · 扣分 {{decision.deduction||0}}</text></view><text class="status">{{statusText(decision.status)}}</text></view><text v-if="decision.summary" class="summary">{{decision.summary}}</text><StatusTimeline :items="decisionTimeline(decision)"/><view v-if="canManage&&decision.key" class="adjust"><picker :range="clauses" :range-key="'title'" :value="clauseSelections[decision.key]||0" @change="chooseClause(decision,$event)"><view class="picker">{{clauseLabel(clauses[clauseSelections[decision.key]||0]||clauses[0])}}</view></picker><view class="actions"><button @click="adjust(decision)">人工调整条款</button><button v-if="decision.status!=='REVOKED'" class="danger" :loading="acting===decision.key" :disabled="Boolean(acting)" @click="revoke(decision)">撤销识别结论</button></view></view></view></view></template></view></template>
<style scoped lang="scss">.page{min-height:100vh;box-sizing:border-box;padding:24rpx;background:#f2f6f5;color:#202124}.header,.section,.notice,.state{padding:24rpx;background:#fff;border:1rpx solid #d9e6e3;border-radius:16rpx}.header,.row,.actions{display:flex;align-items:flex-start;justify-content:space-between;gap:14rpx}.eyebrow,.title,.copy,.section-title,.name,.summary{display:block}.eyebrow,.copy{color:#71807d;font-size:23rpx}.title{margin-top:6rpx;font-size:36rpx;font-weight:750}.score{color:#1f5752;font-size:30rpx;font-weight:750}.section{margin-top:16rpx}.section-title,.name{font-size:28rpx;font-weight:700}.evidence-row,.clause,.decision{margin-top:16rpx;padding-top:16rpx;border-top:1rpx solid #edf0f3}.evidence-row{display:flex;justify-content:space-between;gap:12rpx;color:#4f5661;font-size:23rpx}.decision>.row>view{min-width:0;flex:1}.status{padding:8rpx 11rpx;background:#e6f3f1;color:#1f5752;border-radius:10rpx;font-size:21rpx}.summary{margin:12rpx 0;color:#4f5661;font-size:24rpx;line-height:1.6}.adjust{margin-top:12rpx;padding:14rpx;background:#f7faf9;border-radius:14rpx}.picker{min-height:76rpx;padding:0 16rpx;background:#fff;border:1rpx solid #d9e6e3;border-radius:12rpx;line-height:76rpx;font-size:24rpx}.actions{margin-top:12rpx;justify-content:flex-start}.actions button{margin:0;background:#e6f3f1;color:#1f5752;font-size:23rpx}.actions .danger{background:#fff0ed;color:#963b30}.notice,.state,.empty{text-align:center;color:#71807d}</style>
