package com.storeprofit.system.qmai;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.storeprofit.system.common.BusinessException;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class QmaiConfigServiceMappingTest {
  private JdbcTemplate jdbc;
  private QmaiConfigService service;
  private QmaiProperties properties;

  @BeforeEach
  void setUp() {
    DriverManagerDataSource dataSource = new DriverManagerDataSource(
        "jdbc:h2:mem:qmai-config-" + UUID.randomUUID()
            + ";MODE=MySQL;DB_CLOSE_DELAY=-1", "sa", "");
    jdbc = new JdbcTemplate(dataSource);
    jdbc.execute("""
        create table store_branch (
          tenant_id bigint not null, id varchar(64) not null, name varchar(160),
          primary key (tenant_id, id))
        """);
    jdbc.execute("""
        create table qmai_platform_config (
          id bigint generated by default as identity primary key,
          tenant_id bigint not null, brand varchar(40) not null,
          open_id varchar(2000) not null default '',
          grant_code varchar(2000) not null default '',
          open_key varchar(2000) not null default '',
          base_url varchar(300) not null default '',
          version varchar(40) not null default '',
          shops varchar(4000),
          console_account varchar(2000) not null default '',
          console_password varchar(2000) not null default '',
          console_token varchar(2000),
          updated_by_user_id bigint, updated_by_name varchar(120),
          updated_at timestamp not null default current_timestamp,
          created_at timestamp not null default current_timestamp,
          unique (tenant_id, brand))
        """);
    jdbc.execute("""
        create table qmai_store_mapping (
          id bigint generated by default as identity primary key,
          tenant_id bigint not null, brand_code varchar(40) not null,
          qmai_shop_id varchar(80) not null, qmai_shop_name varchar(160) not null,
          store_id varchar(64) not null,
          unique (tenant_id, brand_code, qmai_shop_id),
          unique (tenant_id, brand_code, store_id))
        """);
    jdbc.update("insert into store_branch values (1, 's1', '一店')");
    jdbc.update("insert into store_branch values (1, 's2', '二店')");
    jdbc.update("insert into store_branch values (2, 's3', '其他租户门店')");

    properties = new QmaiProperties();
    properties.setOpenId("environment-open-id");
    properties.setGrantCode("environment-grant-code");
    properties.setOpenKey("environment-open-key");
    properties.setShops(java.util.List.of("285275:茹果一店:s1"));
    QmaiConfigRepository repository = new QmaiConfigRepository(jdbc);
    service = new QmaiConfigService(
        properties,
        repository,
        new QmaiCredentialCipher(properties),
        new QmaiOutboundPolicy(properties));
  }

  @Test
  void alwaysUsesEnvironmentConfigurationAndNeverReadsDatabaseCredentials() {
    jdbc.update("""
        insert into qmai_platform_config (tenant_id, brand, open_id, grant_code, open_key)
        values (1, 'ruguo', 'database-open-id', 'database-grant-code', 'database-open-key')
        """);

    QmaiConfigService.EffectiveConfig config = service.resolve(1L, "ruguo");

    assertThat(config.openId()).isEqualTo("environment-open-id");
    assertThat(config.grantCode()).isEqualTo("environment-grant-code");
    assertThat(config.openKey()).isEqualTo("environment-open-key");
    assertThat(config.source()).isEqualTo("ENV");
  }

  @Test
  void rejectsWebSaveWithoutChangingHistoricalDatabaseRecords() {
    assertThatThrownBy(() -> service.save(1L, "ruguo", new QmaiConfigService.QmaiConfigForm(
        "new-open-id", "new-grant-code", "new-open-key", null, null, null,
        null, null, null), 7L, "老板"))
        .isInstanceOfSatisfying(BusinessException.class,
            ex -> assertThat(ex.getCode()).isEqualTo("QMAI_ENVIRONMENT_MANAGED"));
    assertThat(jdbc.queryForObject("select count(*) from qmai_platform_config", Integer.class))
        .isEqualTo(0);
  }
}
