package com.storeprofit.system.qmai;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.storeprofit.system.common.BusinessException;
import java.util.Base64;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class QmaiConfigServiceMappingTest {
  private JdbcTemplate jdbc;
  private QmaiConfigService service;
  private QmaiProperties properties;

  @BeforeEach
  void setUp() {
    DriverManagerDataSource dataSource = new DriverManagerDataSource(
        "jdbc:h2:mem:qmai-config-" + UUID.randomUUID()
            + ";MODE=MySQL;DB_CLOSE_DELAY=-1", "sa", "");
    jdbc = new JdbcTemplate(dataSource);
    jdbc.execute("""
        create table store_branch (
          tenant_id bigint not null, id varchar(64) not null, name varchar(160),
          primary key (tenant_id, id))
        """);
    jdbc.execute("""
        create table qmai_platform_config (
          id bigint generated by default as identity primary key,
          tenant_id bigint not null, brand varchar(40) not null,
          open_id varchar(2000) not null default '',
          grant_code varchar(2000) not null default '',
          open_key varchar(2000) not null default '',
          base_url varchar(300) not null default '',
          version varchar(40) not null default '',
          shops varchar(4000),
          console_account varchar(2000) not null default '',
          console_password varchar(2000) not null default '',
          console_token varchar(2000),
          updated_by_user_id bigint, updated_by_name varchar(120),
          updated_at timestamp not null default current_timestamp,
          created_at timestamp not null default current_timestamp,
          unique (tenant_id, brand))
        """);
    jdbc.execute("""
        create table qmai_store_mapping (
          id bigint generated by default as identity primary key,
          tenant_id bigint not null, brand_code varchar(40) not null,
          qmai_shop_id varchar(80) not null, qmai_shop_name varchar(160) not null,
          store_id varchar(64) not null,
          unique (tenant_id, brand_code, qmai_shop_id),
          unique (tenant_id, brand_code, store_id))
        """);
    jdbc.update("insert into store_branch values (1, 's1', '一店')");
    jdbc.update("insert into store_branch values (1, 's2', '二店')");
    jdbc.update("insert into store_branch values (2, 's3', '其他租户门店')");

    properties = new QmaiProperties();
    properties.setCredentialEncryptionKey(
        Base64.getEncoder().encodeToString(new byte[32]));
    QmaiConfigRepository repository = new QmaiConfigRepository(jdbc);
    service = new QmaiConfigService(
        properties,
        repository,
        new QmaiCredentialCipher(properties),
        new QmaiOutboundPolicy(properties));
  }

  @Test
  void canonicalConfigSaveReplacesNormalizedMappingMirror() {
    service.save(1L, "ruguo", form(
        "285275:茹果一店:s1,287952:茹果二店:s2"), 7L, "老板");

    assertThat(service.resolve(1L, "ruguo").shops())
        .containsExactly("285275:茹果一店:s1", "287952:茹果二店:s2");
    assertThat(jdbc.queryForList("""
        select qmai_shop_id, qmai_shop_name, store_id
        from qmai_store_mapping
        where tenant_id = 1 and brand_code = 'ruguo'
        order by qmai_shop_id
        """))
        .extracting(row -> row.get("QMAI_SHOP_ID") + ":" + row.get("STORE_ID"))
        .containsExactly("285275:s1", "287952:s2");

    service.save(1L, "ruguo", new QmaiConfigService.QmaiConfigForm(
        null, null, null, null, null, "287952:更新后的二店:s2",
        null, null, null), 8L, "督导");

    assertThat(service.resolve(1L, "ruguo").shops())
        .containsExactly("287952:更新后的二店:s2");
    assertThat(jdbc.queryForList("""
        select qmai_shop_id, qmai_shop_name, store_id
        from qmai_store_mapping
        where tenant_id = 1 and brand_code = 'ruguo'
        """))
        .singleElement()
        .satisfies(row -> {
          assertThat(row.get("QMAI_SHOP_ID")).isEqualTo("287952");
          assertThat(row.get("QMAI_SHOP_NAME")).isEqualTo("更新后的二店");
          assertThat(row.get("STORE_ID")).isEqualTo("s2");
        });
    assertThat(service.resolve(1L, "ruguo").openId()).isEqualTo("open-id");
  }

  @Test
  void invalidOrCrossTenantMappingIsRejectedBeforeCanonicalConfigChanges() {
    service.save(1L, "ruguo", form("285275:茹果一店:s1"), 7L, "老板");

    for (String invalid : java.util.List.of(
        "285275:缺系统门店",
        "285275:一店:s1,287952:二店:s1",
        "285275:跨租户:s3")) {
      assertThatThrownBy(() ->
          service.save(1L, "ruguo", form(invalid), 7L, "老板"))
          .isInstanceOfSatisfying(BusinessException.class,
              ex -> assertThat(ex.getCode()).isEqualTo("QMAI_SHOP_MAPPING_INVALID"));
    }

    assertThat(service.resolve(1L, "ruguo").shops())
        .containsExactly("285275:茹果一店:s1");
    assertThat(jdbc.queryForObject("""
        select count(*) from qmai_store_mapping
        where tenant_id = 1 and brand_code = 'ruguo'
        """, Integer.class)).isEqualTo(1);
  }

  @Test
  void explicitEmptyDatabaseShopListNeverFallsBackToEnvironmentMappings() {
    properties.setShops(java.util.List.of("999999:旧环境门店:s1"));
    service.save(1L, "ruguo", form("285275:茹果一店:s1"), 7L, "老板");

    service.save(1L, "ruguo", new QmaiConfigService.QmaiConfigForm(
        null, null, null, null, null, "",
        null, null, null), 7L, "老板");

    assertThat(service.resolve(1L, "ruguo").shops()).isEmpty();
    assertThat(jdbc.queryForObject("""
        select count(*) from qmai_store_mapping
        where tenant_id = 1 and brand_code = 'ruguo'
        """, Integer.class)).isZero();
  }

  private QmaiConfigService.QmaiConfigForm form(String shops) {
    return new QmaiConfigService.QmaiConfigForm(
        "open-id", "grant-code", "open-key",
        "https://openapi.qmai.cn", "1.0", shops,
        "", "", "");
  }
}
