<script setup lang="ts">
import { computed, ref } from 'vue'
import { onLoad, onPullDownRefresh } from '@dcloudio/uni-app'
import { getMobileSalary } from '@/api/business'
import { useSessionStore } from '@/stores'
import type { SalaryRecord } from '@/types/business'

const session=useSessionStore(),record=ref<SalaryRecord|null>(null),recordId=ref(''),loading=ref(false),message=ref('')
const canRead=computed(()=>session.hasPermission('salary.read'))
const incomeItems=computed(()=>record.value?[{label:'基本工资',value:record.value.base},{label:'岗位工资',value:record.value.post},{label:'餐补',value:record.value.meal},{label:'全勤奖',value:record.value.fullAttendance},{label:'提成',value:record.value.commission},{label:'加班费',value:record.value.overtime},{label:'工龄工资',value:record.value.seniority},{label:'夜班补贴',value:record.value.lateNight},{label:'其他补贴',value:record.value.subsidy},{label:'绩效',value:record.value.performance}]:[])
const deductionItems=computed(()=>record.value?[{label:'社保',value:record.value.social},{label:'工服扣款',value:record.value.deductUniform},{label:'工服返还',value:record.value.returnUniform}]:[])
onLoad(query=>{recordId.value=String(query?.id||'');void refresh()});onPullDownRefresh(async()=>{await refresh();uni.stopPullDownRefresh()})
async function refresh(){if(!canRead.value||!recordId.value||loading.value)return;loading.value=true;message.value='';try{record.value=await getMobileSalary(recordId.value)}catch(cause){message.value=friendlyError(cause)}finally{loading.value=false}}
function amount(value:unknown){return value===null||value===undefined?'—':`¥${Number(value).toFixed(2)}`}
function number(value:unknown){return value===null||value===undefined?'—':String(value)}
function statusText(status?:string){return({PENDING_GENERATION:'待生成',DRAFT:'草稿',SUBMITTED:'待审核',PENDING_REVIEW:'待审核',APPROVED:'已审核',REJECTED:'已驳回',PAID:'已发放',LOCKED:'已锁定'}as Record<string,string>)[String(status||'')]||status||'—'}
function friendlyError(cause:unknown){const status=Number((cause as{status?:number})?.status||0);return status===403?'当前账号无权查看该工资记录。':status===401?'登录已过期，请重新登录。':'工资详情暂时无法加载。'}
</script>
<template><view class="page"><view v-if="message" class="notice">{{message}}</view><view v-if="!record&&!loading" class="state">工资记录不存在或当前账号无权查看。</view><template v-if="record"><view class="header"><view><text class="eyebrow">{{record.storeName||record.storeId}} · {{record.month}}</text><text class="title">{{record.employeeName}}</text><text class="copy">{{record.position||'员工'}}</text></view><text class="status">{{statusText(record.status)}}</text></view><view class="hero"><text class="hero-label">实发工资</text><text class="hero-value">{{amount(record.netPay)}}</text><text class="copy light">应发 {{amount(record.gross)}}</text></view><view class="metrics"><view><text class="metric">{{number(record.workHours)}}</text><text class="label">工作时长</text></view><view><text class="metric">{{number(record.otHours)}}</text><text class="label">加班时长</text></view><view><text class="metric">{{number(record.vacationLeft)}}</text><text class="label">剩余假期</text></view></view><view class="section"><text class="section-title">收入构成</text><view v-for="item in incomeItems" :key="item.label" class="line"><text>{{item.label}}</text><text>{{amount(item.value)}}</text></view></view><view class="section"><text class="section-title">扣款与返还</text><view v-for="item in deductionItems" :key="item.label" class="line"><text>{{item.label}}</text><text>{{amount(item.value)}}</text></view></view><view class="section"><text class="section-title">流程信息</text><text class="field">当前状态：{{statusText(record.status)}}</text><text class="field">审核时间：{{record.reviewedAt||'—'}}</text><text class="field">发放时间：{{record.paidAt||'—'}}</text><text class="field">审核说明：{{record.reviewNote||'暂无'}}</text><text class="field">考勤说明：{{record.attendance||record.vacationNote||'暂无'}}</text></view></template></view></template>
<style scoped lang="scss">.page{min-height:100vh;box-sizing:border-box;padding:24rpx;background:#f2f6f5;color:#202124}.header,.section,.notice,.state{padding:24rpx;background:#fff;border:1rpx solid #d9e6e3;border-radius:16rpx}.header{display:flex;align-items:flex-start;justify-content:space-between;gap:16rpx}.eyebrow,.title,.copy,.hero-label,.hero-value,.metric,.label,.section-title,.field{display:block}.eyebrow,.copy,.label{color:#71807d;font-size:23rpx}.title{margin-top:6rpx;font-size:36rpx;font-weight:750}.status{padding:10rpx 14rpx;background:#e6f3f1;color:#1f5752;border-radius:12rpx;font-size:23rpx}.hero{margin-top:16rpx;padding:26rpx;background:#27655f;color:#fff;border-radius:16rpx}.hero-label,.light{color:#d9eeea}.hero-value{margin:8rpx 0;font-size:50rpx;font-weight:780}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:12rpx;margin-top:16rpx}.metrics view{padding:20rpx;background:#fff;border:1rpx solid #d9e6e3;border-radius:14rpx}.metric{font-size:30rpx;font-weight:730}.section{margin-top:16rpx}.section-title{font-size:28rpx;font-weight:700}.line{display:flex;justify-content:space-between;gap:12rpx;margin-top:12rpx;color:#4f5661;font-size:24rpx}.field{margin-top:12rpx;color:#4f5661;font-size:24rpx}.notice,.state{text-align:center;color:#71807d}</style>
