<script setup lang="ts">
import { ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { createAdminStore, getAdminStores, updateAdminStore, type MobileStore } from '@/api/admin'
const rows=ref<MobileStore[]>([]), loading=ref(false), editing=ref<MobileStore|null>(null), form=ref({id:'',code:'',name:'',brandId:1,area:'',manager:'',status:'OPEN',note:''})
onShow(()=>{void refresh()}); async function refresh(){loading.value=true;try{rows.value=await getAdminStores()}catch(e){uni.showModal({title:'加载失败',content:'门店数据暂时无法加载',showCancel:false})}finally{loading.value=false}}
function edit(row?:MobileStore){uni.pageScrollTo({scrollTop:0,duration:180});editing.value=row||null;form.value={id:row?.id||'',code:row?.code||'',name:row?.name||'',brandId:row?.brandId||1,area:row?.area||'',manager:row?.manager||'',status:row?.status||'OPEN',note:row?.note||''}}
const statusOptions=['营业中','已关闭','暂停营业']
function chooseStatus(e:{detail:{value:number|string}}){form.value.status=['OPEN','CLOSED','SUSPENDED'][Number(e.detail.value)]||form.value.status}
function statusLabel(status:string){return ({OPEN:'营业中',CLOSED:'已关闭',SUSPENDED:'暂停营业'} as Record<string,string>)[status]||status}
async function save(){if(!form.value.name.trim()){uni.showToast({title:'请填写门店名称',icon:'none'});return}try{if(editing.value)await updateAdminStore(form.value);else await createAdminStore(form.value);uni.showToast({title:'保存成功',icon:'success'});editing.value=null;await refresh()}catch(e){uni.showModal({title:'保存失败',content:'请检查权限或填写内容',showCancel:false})}}
</script>
<template><view class="page"><view class="head"><text class="title">门店管理</text><button @click="edit()">新增门店</button></view><view v-if="editing" class="form"><input v-model="form.code" placeholder="门店编号"/><input v-model="form.name" placeholder="门店名称"/><input v-model="form.area" placeholder="区域"/><input v-model="form.manager" placeholder="负责人"/><picker :range="statusOptions" @change="chooseStatus"><view class="select">状态：{{statusLabel(form.status)}}⌄</view></picker><input v-model="form.note" placeholder="备注"/><view class="actions"><button @click="editing=null">取消</button><button class="primary" @click="save">保存</button></view></view><view v-for="row in rows" :key="row.id" class="card"><view><text class="name">{{row.name}}</text><text class="muted">{{row.code}} · {{row.area||'未填写区域'}} · {{row.status||'未知状态'}}</text><text class="muted">负责人：{{row.manager||'未设置'}}</text></view><button @click="edit(row)">编辑</button></view><view v-if="!rows.length&&!loading" class="empty">暂无门店</view></view></template>
<style scoped lang="scss">.page{min-height:100vh;padding:24rpx 24rpx 150rpx;background:#f2f6f5}.head,.card,.actions{display:flex;align-items:center;justify-content:space-between;gap:14rpx}.title{font-size:38rpx;font-weight:800}.head button,.primary{background:#27655f;color:#fff}.form,.card{margin-top:16rpx;padding:22rpx;background:#fff;border-radius:16rpx}.form input,.select{margin:12rpx 0;padding:18rpx;background:#f6f8f8;border-radius:10rpx}.select{border:1rpx solid #a9c8c3;color:#27655f}.name,.muted{display:block}.name{font-size:29rpx;font-weight:700}.muted{margin-top:8rpx;color:#71807d;font-size:23rpx}.actions{position:sticky;bottom:0;z-index:10;justify-content:flex-end;margin:18rpx -22rpx -22rpx;padding:18rpx 22rpx calc(18rpx + env(safe-area-inset-bottom));background:rgba(255,255,255,.96);border-top:1rpx solid #d9e6e3}.empty{text-align:center;padding:50rpx;color:#71807d}</style>
