<script setup lang="ts">
import{computed,ref}from'vue';import{onPullDownRefresh,onShow}from'@dcloudio/uni-app';import{approveMobileDailyLoss,createMobileDailyLoss,getMobileDailyLossItems,getMobileDailyLossRecords,submitMobileDailyLoss,uploadMobileDailyLossAttachment}from'@/api/business';import{chooseMedia}from'@/platform';import{useContextStore,useSessionStore}from'@/stores';import type{DailyLossItem,DailyLossRecord}from'@/types/business';import{canPerformMobileAction}from'@/permissions';import ProtectedAttachmentList from'@/components/ProtectedAttachmentList.vue'
const session=useSessionStore(),context=useContextStore(),items=ref<DailyLossItem[]>([]),rows=ref<DailyLossRecord[]>([]),selected=ref(0),qty=ref(''),reason=ref(''),lossDate=ref(new Date().toISOString().slice(0,10)),filterStatus=ref('ALL'),message=ref(''),acting=ref(false),photos=ref<Array<{path:string}>>([]);const canCreate=computed(()=>canPerformMobileAction(session.user,'dailyLoss.create')),canReview=computed(()=>canPerformMobileAction(session.user,'dailyLoss.review'))
onShow(async()=>{if(!context.stores.length&&session.user)await context.load(session.user);await refresh()});onPullDownRefresh(async()=>{await refresh();uni.stopPullDownRefresh()});async function refresh(){try{[items.value,rows.value]=await Promise.all([getMobileDailyLossItems(),getMobileDailyLossRecords({storeId:context.currentStoreId||undefined,status:filterStatus.value==='ALL'?undefined:filterStatus.value})])}catch(e){message.value=e instanceof Error?e.message:'报损加载失败'}}
async function selectPhotos(){photos.value=await chooseMedia({count:3,source:'both',kinds:['image']})}
async function create(){if(!canCreate.value)return;const storeId=context.currentStoreId||session.user?.boundStoreId||'',item=items.value[selected.value];if(!storeId||!item||!Number(qty.value)||!reason.value.trim()||!lossDate.value){message.value='请完整填写发生日期、物料、数量和原因。';return}acting.value=true;try{let r=await createMobileDailyLoss({storeId,lossDate:lossDate.value,itemId:item.id,lossQuantity:Number(qty.value),lossReason:reason.value});for(const photo of photos.value)r=await uploadMobileDailyLossAttachment(r.id,photo.path);await submitMobileDailyLoss(r.id);qty.value='';reason.value='';photos.value=[];await refresh()}catch(e){message.value=e instanceof Error?e.message:'提交失败'}finally{acting.value=false}}
async function approve(r:DailyLossRecord){if(!canReview.value)return;await approveMobileDailyLoss(r.id,'移动端审核通过');await refresh()}
</script><template><view class="page"><text class="title">每日报损</text><view v-if="message" class="notice">{{message}}</view><view v-if="canCreate" class="panel"><picker mode="date" :value="lossDate" @change="lossDate=String($event.detail.value)"><view class="input">发生日期：{{lossDate}}</view></picker><picker :range="items" range-key="name" @change="selected=Number($event.detail.value)"><view class="input">{{items[selected]?.name||'选择报损物料'}}</view></picker><input v-model="qty" class="input" type="digit" placeholder="报损数量"/><textarea v-model="reason" class="input area" placeholder="报损原因"/><button class="plain" @click="selectPhotos">选择现场照片（{{photos.length}}/3）</button><button class="primary" :loading="acting" @click="create">提交报损</button></view><view class="filters"><button v-for="status in ['ALL','SUBMITTED','APPROVED']" :key="status" :class="{active:filterStatus===status}" @click="filterStatus=status;refresh()">{{status==='ALL'?'全部':status==='SUBMITTED'?'待审核':'已通过'}}</button></view><view v-for="r in rows" :key="r.id" class="card"><view class="row"><text class="name">{{r.itemName}}</text><text>{{r.status}}</text></view><text class="copy">{{r.lossDate}} · {{r.lossQuantity}}{{r.stockUnit}} · ¥{{Number(r.amountSnapshot||0).toFixed(2)}}</text><text class="copy">{{r.lossReason}}</text><ProtectedAttachmentList :items="(r.attachments||[]).map(a=>({id:a.id,fileName:a.fileName,contentType:a.contentType,path:a.downloadUrl}))" @error="message=$event"/><button v-if="canReview&&r.status==='SUBMITTED'" @click="approve(r)">审核通过</button></view></view></template>
<style scoped lang="scss">.page{min-height:100vh;padding:24rpx;background:#f2f6f5}.title{font-size:40rpx;font-weight:750}.panel,.card,.notice{margin-top:18rpx;padding:24rpx;background:#fff;border:1rpx solid #d9e6e3;border-radius:16rpx}.input{box-sizing:border-box;width:100%;margin-top:14rpx;padding:20rpx;background:#f7faf9;border-radius:12rpx}.area{height:130rpx}.primary{background:#27655f;color:#fff}.row{display:flex;justify-content:space-between}.name,.copy{display:block}.name{font-weight:700}.copy{margin-top:10rpx;color:#71807d;font-size:24rpx}.filters{display:flex;gap:10rpx;margin-top:18rpx}.filters button{margin:0;background:#fff;color:#59606b;font-size:23rpx}.filters button.active{background:#e6f3f1;color:#1f5752}</style>
