<script setup lang="ts">
import { computed, ref } from 'vue'
import { onPullDownRefresh, onShow } from '@dcloudio/uni-app'
import { approveMobileDailyLoss, createMobileDailyLoss, getMobileDailyLossItems, getMobileDailyLossRecords, submitMobileDailyLoss, uploadMobileDailyLossAttachment } from '@/api/business'
import ProtectedAttachmentList from '@/components/ProtectedAttachmentList.vue'
import { canPerformMobileAction } from '@/permissions'
import { chooseMedia, openProtectedFile } from '@/platform'
import { useContextStore, useSessionStore } from '@/stores'
import type { DailyLossItem, DailyLossRecord } from '@/types/business'

const session = useSessionStore(); const context = useContextStore()
const items = ref<DailyLossItem[]>([]); const rows = ref<DailyLossRecord[]>([]); const selected = ref(0)
const qty = ref(''); const reason = ref(''); const lossDate = ref(new Date().toISOString().slice(0, 10)); const filterStatus = ref('ALL')
const message = ref(''); const acting = ref(false); const photos = ref<Array<{ path: string }>>([]); const exporting = ref(false); const exportMonth = ref(new Date().toISOString().slice(0, 7))
const canCreate = computed(() => canPerformMobileAction(session.user, 'dailyLoss.create')); const canReview = computed(() => canPerformMobileAction(session.user, 'dailyLoss.review')); const canExport = computed(() => session.hasPermission('daily_loss.export'))
onShow(async () => { if (!context.stores.length && session.user) await context.load(session.user); await refresh() })
onPullDownRefresh(async () => { await refresh(); uni.stopPullDownRefresh() })
async function refresh() { try { [items.value, rows.value] = await Promise.all([getMobileDailyLossItems(), getMobileDailyLossRecords({ storeId: context.currentStoreId || undefined, status: filterStatus.value === 'ALL' ? undefined : filterStatus.value })]) } catch (error) { message.value = error instanceof Error ? error.message : '报损加载失败' } }
async function selectPhotos() { photos.value = await chooseMedia({ count: 3, source: 'both', kinds: ['image'] }) }
async function create() { if (!canCreate.value) return; const storeId = context.currentStoreId || session.user?.boundStoreId || ''; const item = items.value[selected.value]; if (!storeId || !item || !Number(qty.value) || !reason.value.trim() || !lossDate.value) { message.value = '请完整填写发生日期、物料、数量和原因。'; return } acting.value = true; try { let record = await createMobileDailyLoss({ storeId, lossDate: lossDate.value, itemId: item.id, lossQuantity: Number(qty.value), lossReason: reason.value }); for (const photo of photos.value) record = await uploadMobileDailyLossAttachment(record.id, photo.path); await submitMobileDailyLoss(record.id); qty.value = ''; reason.value = ''; photos.value = []; await refresh() } catch (error) { message.value = error instanceof Error ? error.message : '提交失败' } finally { acting.value = false } }
async function approve(row: DailyLossRecord) { if (!canReview.value) return; await approveMobileDailyLoss(row.id, '移动端审核通过'); await refresh() }
async function exportMonthFile() { if (!canExport.value || exporting.value) return; exporting.value = true; try { const storeId = context.currentStoreId || session.user?.boundStoreId || ''; const query = `month=${encodeURIComponent(exportMonth.value)}${storeId ? `&storeId=${encodeURIComponent(storeId)}` : ''}`; await openProtectedFile({ path: `/api/daily-loss/exports/monthly.xlsx?${query}`, fileName: `${exportMonth.value}报损.xlsx`, contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }) } catch (error) { message.value = error instanceof Error ? error.message : '报损 Excel 导出失败' } finally { exporting.value = false } }
</script>
<template><view class="page"><view class="head"><text class="title">每日报损</text><button v-if="canExport" :loading="exporting" @click="exportMonthFile">导出 Excel</button></view><view v-if="canExport" class="export"><picker mode="date" fields="month" :value="exportMonth" @change="exportMonth=String($event.detail.value)"><view>导出月份：{{exportMonth}} ›</view></picker></view><view v-if="message" class="notice">{{message}}</view><view v-if="canCreate" class="panel"><picker mode="date" :value="lossDate" @change="lossDate=String($event.detail.value)"><view class="input">发生日期：{{lossDate}}</view></picker><picker :range="items" range-key="name" @change="selected=Number($event.detail.value)"><view class="input">{{items[selected]?.name||'选择报损物料'}}</view></picker><input v-model="qty" class="input" type="digit" placeholder="报损数量"/><textarea v-model="reason" class="input area" placeholder="报损原因"/><button class="plain" @click="selectPhotos">选择现场照片（{{photos.length}}/3）</button><button class="primary" :loading="acting" @click="create">提交报损</button></view><view class="filters"><button v-for="status in ['ALL','SUBMITTED','APPROVED']" :key="status" :class="{active:filterStatus===status}" @click="filterStatus=status;refresh()">{{status==='ALL'?'全部':status==='SUBMITTED'?'待审核':'已通过'}}</button></view><view v-for="row in rows" :key="row.id" class="card"><view class="row"><text class="name">{{row.itemName}}</text><text>{{row.status}}</text></view><text class="copy">{{row.lossDate}} · {{row.lossQuantity}}{{row.stockUnit}} · ¥{{Number(row.amountSnapshot||0).toFixed(2)}}</text><text class="copy">{{row.lossReason}}</text><ProtectedAttachmentList :items="(row.attachments||[]).map(a=>({id:a.id,fileName:a.fileName,contentType:a.contentType,path:a.downloadUrl}))" @error="message=$event"/><button v-if="canReview&&row.status==='SUBMITTED'" @click="approve(row)">审核通过</button></view></view></template>
<style scoped lang="scss">.page{min-height:100vh;padding:24rpx;background:#f2f6f5}.head,.row{display:flex;align-items:center;justify-content:space-between;gap:12rpx}.title{font-size:40rpx;font-weight:750}.head button{margin:0;background:#e6f3f1;color:#1f5752;font-size:23rpx}.export,.panel,.card,.notice{margin-top:18rpx;padding:24rpx;background:#fff;border:1rpx solid #d9e6e3;border-radius:16rpx}.export{color:#1f5752;font-size:24rpx}.input{box-sizing:border-box;width:100%;margin-top:14rpx;padding:20rpx;background:#f7faf9;border-radius:12rpx}.area{height:130rpx}.primary{background:#27655f;color:#fff}.name,.copy{display:block}.name{font-weight:700}.copy{margin-top:10rpx;color:#71807d;font-size:24rpx}.filters{display:flex;gap:10rpx;margin-top:18rpx}.filters button{margin:0;background:#fff;color:#59606b;font-size:23rpx}.filters button.active{background:#e6f3f1;color:#1f5752}</style>
