-- H2 verification equivalent of MySQL V105.
-- Group existing and future knowledge documents into auditable topics and versions.

create table knowledge_base_topic (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  name varchar(200) not null,
  normalized_name varchar(200) not null,
  created_by bigint not null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  constraint uk_knowledge_base_topic_name unique (tenant_id, normalized_name)
);
create index idx_knowledge_base_topic_list
  on knowledge_base_topic(tenant_id, updated_at, id);

insert into knowledge_base_topic(
  tenant_id, name, normalized_name, created_by, created_at, updated_at
)
select
  tenant_id,
  min(title),
  lower(trim(title)),
  min(created_by),
  min(created_at),
  max(updated_at)
from knowledge_base_document
group by tenant_id, lower(trim(title));

alter table knowledge_base_document add column topic_id bigint;
alter table knowledge_base_document add column version_no int;
alter table knowledge_base_document add column relation_type varchar(16);
alter table knowledge_base_document add column predecessor_document_id bigint;

update knowledge_base_document document
set document.topic_id = (
  select topic.id from knowledge_base_topic topic
  where topic.tenant_id = document.tenant_id
    and topic.normalized_name = lower(trim(document.title))
);

update knowledge_base_document document
set document.version_no = (
  select count(*) + 1
  from knowledge_base_document earlier
  where earlier.topic_id = document.topic_id
    and (earlier.created_at < document.created_at
         or (earlier.created_at = document.created_at and earlier.id < document.id))
),
document.predecessor_document_id = (
  select max(earlier.id)
  from knowledge_base_document earlier
  where earlier.topic_id = document.topic_id
    and (earlier.created_at < document.created_at
         or (earlier.created_at = document.created_at and earlier.id < document.id))
);

update knowledge_base_document
set relation_type = case when version_no = 1 then 'ORIGINAL' else 'SUPPLEMENTS' end;

alter table knowledge_base_document alter column topic_id bigint not null;
alter table knowledge_base_document alter column version_no int not null;
alter table knowledge_base_document alter column relation_type varchar(16) not null;

alter table knowledge_base_document
  add constraint uk_knowledge_base_document_topic_version unique (topic_id, version_no);
create index idx_knowledge_base_document_topic_status
  on knowledge_base_document(tenant_id, topic_id, status, version_no);
create index idx_knowledge_base_document_predecessor
  on knowledge_base_document(predecessor_document_id);
alter table knowledge_base_document
  add constraint fk_knowledge_base_document_topic
    foreign key (topic_id) references knowledge_base_topic(id);
alter table knowledge_base_document
  add constraint fk_knowledge_base_document_predecessor
    foreign key (predecessor_document_id) references knowledge_base_document(id);
alter table knowledge_base_document
  add constraint chk_knowledge_base_document_version check (version_no > 0);
alter table knowledge_base_document
  add constraint chk_knowledge_base_document_relation
    check (relation_type in ('ORIGINAL', 'REPLACES', 'SUPPLEMENTS'));
