-- H2 verification equivalent of MySQL V110.20260727154006001.
create table qmai_inventory_snapshot (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  brand_code varchar(40) not null,
  snapshot_date date not null,
  captured_at timestamp not null,
  source_total bigint not null,
  row_count int not null,
  created_at timestamp not null default current_timestamp,
  constraint uk_qmai_inventory_snapshot_latest unique (tenant_id, brand_code),
  constraint chk_qmai_inventory_snapshot_total check (source_total >= 0 and row_count >= 0),
  constraint fk_qmai_inventory_snapshot_tenant
    foreign key (tenant_id) references tenant(id)
);

create index idx_qmai_inventory_snapshot_date
  on qmai_inventory_snapshot(tenant_id, snapshot_date);

create table qmai_inventory_snapshot_item (
  id bigint generated by default as identity primary key,
  snapshot_id bigint not null,
  line_no int not null,
  warehouse_id varchar(120) null,
  warehouse_no varchar(200) null,
  warehouse_name varchar(300) null,
  org_name varchar(300) null,
  product_id varchar(120) null,
  product_code varchar(200) null,
  product_name varchar(1000) null,
  product_spec varchar(1000) null,
  order_unit varchar(120) null,
  stock_unit varchar(120) null,
  consume_unit varchar(120) null,
  purchase_unit varchar(120) null,
  export_unit varchar(120) null,
  category_id varchar(120) null,
  category_name varchar(300) null,
  quantity decimal(38,18) null,
  available_quantity decimal(38,18) null,
  current_amount decimal(38,18) null,
  estimate_num decimal(38,18) null,
  occupy_quantity decimal(38,18) null,
  cost_price decimal(38,18) null,
  estimate_inbound_num decimal(38,18) null,
  constraint uk_qmai_inventory_snapshot_line unique (snapshot_id, line_no),
  constraint fk_qmai_inventory_snapshot_item
    foreign key (snapshot_id) references qmai_inventory_snapshot(id) on delete cascade
);

create index idx_qmai_inventory_snapshot_warehouse
  on qmai_inventory_snapshot_item(snapshot_id, warehouse_no);
create index idx_qmai_inventory_snapshot_product
  on qmai_inventory_snapshot_item(snapshot_id, product_code);

create table qmai_inventory_sync_lease (
  tenant_id bigint not null,
  brand_code varchar(40) not null,
  lock_token varchar(64) not null,
  locked_until timestamp not null,
  updated_at timestamp not null default current_timestamp,
  primary key (tenant_id, brand_code),
  constraint fk_qmai_inventory_lease_tenant
    foreign key (tenant_id) references tenant(id)
);

create index idx_qmai_inventory_lease_expiry
  on qmai_inventory_sync_lease(locked_until);
