create table if not exists daily_loss_peel_profile (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  primary_item_config_id bigint not null,
  peeled_item_config_id bigint,
  unpeeled_item_config_id bigint,
  canonical_name varchar(160) not null,
  default_peel_state varchar(20) not null,
  yield_rate decimal(12,9),
  gross_grams_per_unit decimal(18,4),
  inventory_unit varchar(20) not null,
  source_price_file varchar(255) not null,
  source_formula_file varchar(255) not null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp,
  constraint uk_daily_loss_peel_profile_primary unique (tenant_id, primary_item_config_id),
  constraint chk_daily_loss_peel_profile_default
    check (default_peel_state in ('PEELED', 'UNPEELED')),
  constraint chk_daily_loss_peel_profile_yield
    check (yield_rate is null or (yield_rate > 0 and yield_rate <= 1)),
  constraint chk_daily_loss_peel_profile_gross
    check (gross_grams_per_unit is null or gross_grams_per_unit > 0),
  constraint chk_daily_loss_peel_profile_price
    check (peeled_item_config_id is not null or unpeeled_item_config_id is not null)
);

create index if not exists idx_daily_loss_peel_profile_peeled
  on daily_loss_peel_profile(tenant_id, peeled_item_config_id);
create index if not exists idx_daily_loss_peel_profile_unpeeled
  on daily_loss_peel_profile(tenant_id, unpeeled_item_config_id);

alter table daily_loss_record add column if not exists peel_state_snapshot varchar(20);
alter table daily_loss_record add column if not exists price_basis_snapshot varchar(20);
alter table daily_loss_record add column if not exists yield_rate_snapshot decimal(12,9);
alter table daily_loss_record add column if not exists inventory_quantity_snapshot decimal(18,4);
alter table daily_loss_record add column if not exists inventory_unit_snapshot varchar(20);

update daily_loss_record
set inventory_quantity_snapshot = loss_quantity,
    inventory_unit_snapshot = stock_unit
where inventory_quantity_snapshot is null;

alter table daily_loss_inventory_application
  alter column quantity decimal(18,4) not null;
