create table if not exists business_todo (
  id varchar(120) not null primary key,
  tenant_id bigint not null,
  rule_code varchar(80) not null,
  source_module varchar(80) not null,
  source_record_id varchar(160) not null,
  source_key varchar(100) not null,
  occurrence_no int not null default 1,
  title varchar(255) not null,
  summary text null,
  assignee_role varchar(40) not null,
  review_role varchar(40) null,
  store_id varchar(64) null,
  month char(7) null,
  priority tinyint not null default 1,
  status varchar(40) not null default 'PENDING',
  condition_active tinyint not null default 1,
  metadata_json longtext null,
  last_operator_id bigint null,
  last_operator_name varchar(120) null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp null default null,
  completed_at timestamp null,
  unique key uq_business_todo_occurrence (tenant_id, rule_code, source_key, occurrence_no),
  index idx_business_todo_visible (tenant_id, status, assignee_role, review_role, updated_at),
  index idx_business_todo_store_month (tenant_id, store_id, month),
  constraint fk_business_todo_tenant foreign key (tenant_id) references tenant(id)
);
