create table if not exists training_course (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  course_code varchar(80) not null,
  title varchar(160) not null,
  category varchar(80),
  description clob,
  cover_url varchar(500),
  duration_minutes int not null default 0,
  required_role_scope varchar(255),
  enabled boolean not null default true,
  sort_order int not null default 0,
  created_by bigint,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp,
  constraint uk_training_course_code unique (tenant_id, course_code)
);

create table if not exists training_course_material (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  course_id bigint not null,
  material_id bigint not null,
  required boolean not null default true,
  sort_order int not null default 0,
  created_at timestamp not null default current_timestamp,
  constraint uk_training_course_material unique (tenant_id, course_id, material_id)
);

create table if not exists training_exam_question_category (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  category_code varchar(80) not null,
  category_name varchar(120) not null,
  description varchar(500),
  enabled boolean not null default true,
  sort_order int not null default 0,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp,
  constraint uk_exam_question_category_code unique (tenant_id, category_code)
);

create table if not exists training_exam_question_bank (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  question_code varchar(100) not null,
  category_id bigint,
  question_type varchar(40) not null,
  question_text clob not null,
  options_json clob,
  standard_answer clob,
  answer_analysis clob,
  accept_keywords clob,
  difficulty varchar(20) not null default 'MEDIUM',
  default_score decimal(8,2) not null default 10,
  enabled boolean not null default true,
  created_by bigint,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp,
  constraint uk_exam_question_bank_code unique (tenant_id, question_code)
);

create table if not exists training_exam_paper_question_link (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  paper_question_id bigint not null,
  bank_question_id bigint not null,
  created_at timestamp not null default current_timestamp,
  constraint uk_exam_paper_question_link unique (tenant_id, paper_question_id)
);

create table if not exists training_exam_attempt_review (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  attempt_id bigint not null,
  review_status varchar(40) not null default 'AUTO_GRADED',
  review_note varchar(500),
  reviewed_by bigint,
  reviewed_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp,
  constraint uk_exam_attempt_review unique (tenant_id, attempt_id)
);

create table if not exists training_exam_answer_review (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  answer_id bigint not null,
  awarded_score decimal(8,2) not null default 0,
  review_comment varchar(500),
  reviewed_by bigint not null,
  reviewed_at timestamp not null,
  created_at timestamp not null default current_timestamp,
  constraint uk_exam_answer_review unique (tenant_id, answer_id)
);

create table if not exists training_exam_wrong_question (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  user_id bigint not null,
  attempt_id bigint not null,
  question_id bigint not null,
  mastered boolean not null default false,
  mastered_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp,
  constraint uk_exam_wrong_question unique (tenant_id, user_id, attempt_id, question_id)
);

merge into training_exam_question_category c
using (select id as tenant_id from tenant) t
on c.tenant_id = t.tenant_id and c.category_code = 'GENERAL'
when not matched then insert (tenant_id, category_code, category_name, description, enabled, sort_order, created_at, updated_at)
values (t.tenant_id, 'GENERAL', '基础知识', '通用制度、品牌与岗位基础知识', true, 10, current_timestamp, current_timestamp);

merge into training_exam_question_category c
using (select id as tenant_id from tenant) t
on c.tenant_id = t.tenant_id and c.category_code = 'FOOD_SAFETY'
when not matched then insert (tenant_id, category_code, category_name, description, enabled, sort_order, created_at, updated_at)
values (t.tenant_id, 'FOOD_SAFETY', '食品安全', '食品储存、加工、效期和卫生规范', true, 20, current_timestamp, current_timestamp);

merge into training_exam_question_category c
using (select id as tenant_id from tenant) t
on c.tenant_id = t.tenant_id and c.category_code = 'SERVICE'
when not matched then insert (tenant_id, category_code, category_name, description, enabled, sort_order, created_at, updated_at)
values (t.tenant_id, 'SERVICE', '服务规范', '顾客接待、点单、出餐和投诉处理', true, 30, current_timestamp, current_timestamp);

merge into training_exam_question_category c
using (select id as tenant_id from tenant) t
on c.tenant_id = t.tenant_id and c.category_code = 'STORE_OPERATION'
when not matched then insert (tenant_id, category_code, category_name, description, enabled, sort_order, created_at, updated_at)
values (t.tenant_id, 'STORE_OPERATION', '门店运营', '盘存、陈列和门店日常运营标准', true, 40, current_timestamp, current_timestamp);
