alter table auth_user add column if not exists permission_version bigint not null default 1;
alter table auth_token add column if not exists permission_version bigint not null default 1;

create table if not exists permission_catalog (
  permission_code varchar(120) not null primary key,
  module_code varchar(40) not null,
  permission_name varchar(120) not null,
  description varchar(500) null,
  risk_level varchar(16) not null default 'LOW',
  enabled tinyint(1) not null default 1,
  sort_order int not null default 0,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp null default null,
  constraint chk_permission_catalog_risk check (risk_level in ('LOW', 'MEDIUM', 'HIGH'))
);

create index if not exists idx_permission_catalog_module
  on permission_catalog(module_code, sort_order);
create index if not exists idx_permission_catalog_enabled
  on permission_catalog(enabled, module_code);

create table if not exists user_permission_override (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  user_id bigint not null,
  permission_code varchar(120) not null,
  effect varchar(16) not null,
  created_by bigint null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp null default null,
  constraint uk_user_permission_override unique (tenant_id, user_id, permission_code),
  constraint chk_user_permission_override_effect check (effect in ('ALLOW', 'DENY')),
  constraint fk_user_permission_override_tenant foreign key (tenant_id) references tenant(id),
  constraint fk_user_permission_override_user foreign key (user_id) references auth_user(id) on delete cascade,
  constraint fk_user_permission_override_permission foreign key (permission_code) references permission_catalog(permission_code),
  constraint fk_user_permission_override_creator foreign key (created_by) references auth_user(id) on delete set null
);

create index if not exists idx_user_permission_override_effect
  on user_permission_override(tenant_id, user_id, effect);
create index if not exists idx_user_permission_override_permission
  on user_permission_override(permission_code);

create table if not exists user_data_scope (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  user_id bigint not null,
  domain_code varchar(40) not null,
  scope_type varchar(32) not null,
  scope_value_json longtext null,
  created_by bigint null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp null default null,
  constraint uk_user_data_scope unique (tenant_id, user_id, domain_code),
  constraint chk_user_data_scope_domain check (
    domain_code in ('STORE', 'FINANCE', 'SALARY', 'WAREHOUSE', 'INSPECTION', 'EXAM', 'PLATFORM')
  ),
  constraint chk_user_data_scope_type check (
    scope_type in ('ALL', 'STORE_LIST', 'OWN_STORE', 'NONE', 'CENTRAL_WAREHOUSE', 'SELF')
  ),
  constraint chk_user_data_scope_payload check (
    (scope_type = 'STORE_LIST' and scope_value_json is not null)
    or (scope_type <> 'STORE_LIST' and scope_value_json is null)
  ),
  constraint fk_user_data_scope_tenant foreign key (tenant_id) references tenant(id),
  constraint fk_user_data_scope_user foreign key (user_id) references auth_user(id) on delete cascade,
  constraint fk_user_data_scope_creator foreign key (created_by) references auth_user(id) on delete set null
);

create index if not exists idx_user_data_scope_domain
  on user_data_scope(tenant_id, domain_code, scope_type);

insert into permission_catalog(
  permission_code, module_code, permission_name, description, risk_level, enabled, sort_order
)
values
  ('system.dashboard.read', 'SYSTEM', '查看老板工作台', '进入老板工作台并查看全公司概览。', 'LOW', 1, 10),
  ('system.user.manage', 'SYSTEM', '管理账号权限', '创建账号、修改角色、配置权限和数据范围。', 'HIGH', 1, 20),
  ('system.audit.read', 'SYSTEM', '查看操作审计', '查看操作日志、权限拒绝和敏感操作记录。', 'HIGH', 1, 30),
  ('system.audit.write', 'SYSTEM', '补写操作审计', '补写经批准的系统操作审计记录。', 'HIGH', 1, 40),
  ('system.migration.manage', 'SYSTEM', '执行系统迁移', '执行受控的数据迁移和兼容处理。', 'HIGH', 1, 50),
  ('operations.dashboard.read', 'OPERATIONS', '查看运营工作台', '查看巡店、考试、平台和运营待办概览。', 'LOW', 1, 60),
  ('assistant.use', 'ASSISTANT', '使用经营助手', '在当前账号权限和数据范围内使用经营助手。', 'MEDIUM', 1, 70),
  ('store.read', 'STORE', '查看门店', '查看权限范围内的门店基础信息。', 'LOW', 1, 100),
  ('store.manage', 'STORE', '维护门店', '维护权限范围内的门店资料和运营配置。', 'MEDIUM', 1, 110),
  ('employee.read', 'EMPLOYEE', '查看员工', '查看权限范围内的员工基础资料。', 'MEDIUM', 1, 120),
  ('employee.manage', 'EMPLOYEE', '维护员工', '新增或维护权限范围内的员工资料。', 'HIGH', 1, 130),
  ('finance.profit.read', 'FINANCE', '查看利润', '查看权限范围内的经营利润和成本。', 'MEDIUM', 1, 200),
  ('finance.profit.write', 'FINANCE', '维护利润', '录入或修改权限范围内的经营数据。', 'HIGH', 1, 210),
  ('finance.profit.delete', 'FINANCE', '删除利润记录', '删除经确认可移除的经营利润记录。', 'HIGH', 1, 220),
  ('finance.export', 'FINANCE', '导出财务数据', '导出利润、工资或其他敏感经营数据。', 'HIGH', 1, 230),
  ('expense.create', 'EXPENSE', '提交报销', '创建报销单并补充报销资料。', 'MEDIUM', 1, 300),
  ('expense.read', 'EXPENSE', '查看报销', '查看权限范围内的报销单。', 'MEDIUM', 1, 310),
  ('expense.review', 'EXPENSE', '审核报销', '审核、退回或确认报销单。', 'HIGH', 1, 320),
  ('salary.read', 'SALARY', '查看工资', '查看权限范围内的工资记录。', 'HIGH', 1, 400),
  ('salary.edit', 'SALARY', '编辑工资', '生成或修改工资记录。', 'HIGH', 1, 410),
  ('salary.review', 'SALARY', '审核工资', '审核或退回工资记录。', 'HIGH', 1, 420),
  ('salary.pay', 'SALARY', '确认工资发放', '将审核通过的工资标记为已发放。', 'HIGH', 1, 430),
  ('warehouse.central.read', 'WAREHOUSE', '查看总仓库存', '查看总仓物料、批次、采购和出入库信息。', 'MEDIUM', 1, 500),
  ('warehouse.central.manage', 'WAREHOUSE', '管理总仓库存', '维护总仓物料、采购、入库、调拨、退货和库存。', 'HIGH', 1, 510),
  ('warehouse.store.read', 'WAREHOUSE', '查看门店库存', '查看权限范围内的门店库存和叫货信息。', 'LOW', 1, 520),
  ('warehouse.requisition.create', 'WAREHOUSE', '创建叫货申请', '为绑定门店创建叫货或配送退货申请。', 'MEDIUM', 1, 530),
  ('warehouse.requisition.review', 'WAREHOUSE', '审核叫货申请', '审核门店叫货申请并安排配送。', 'HIGH', 1, 540),
  ('warehouse.requisition.receive', 'WAREHOUSE', '确认门店收货', '确认绑定门店的配送收货结果。', 'MEDIUM', 1, 550),
  ('inventory.read', 'INVENTORY', '查看盘存', '查看权限范围内的盘存单。', 'LOW', 1, 560),
  ('inventory.manage', 'INVENTORY', '维护盘存', '创建或修改权限范围内的盘存单。', 'MEDIUM', 1, 570),
  ('inventory.review', 'INVENTORY', '复核盘存', '复核权限范围内的盘存单。', 'HIGH', 1, 580),
  ('inspection.read', 'INSPECTION', '查看巡店', '查看权限范围内的巡店记录和整改结果。', 'LOW', 1, 600),
  ('inspection.manage', 'INSPECTION', '管理巡店', '发起巡店、评分、整改复核和红线处理。', 'HIGH', 1, 610),
  ('exam.learn', 'EXAM', '参加培训考试', '查看本人课程、考试任务和学习记录。', 'LOW', 1, 700),
  ('exam.manage', 'EXAM', '管理培训考试', '维护课程、题库、考试发布和阅卷。', 'HIGH', 1, 710),
  ('exam.report', 'EXAM', '查看培训报表', '查看权限范围内的培训进度和考试报表。', 'MEDIUM', 1, 720),
  ('platform.read', 'PLATFORM', '查看平台配置', '查看权限范围内的平台配置和同步状态。', 'MEDIUM', 1, 800),
  ('platform.manage', 'PLATFORM', '管理平台授权', '维护第三方平台授权、同步配置和回调设置。', 'HIGH', 1, 810),
  ('attachment.read', 'ATTACHMENT', '查看附件', '查看权限范围内的业务附件。', 'MEDIUM', 1, 900),
  ('attachment.write', 'ATTACHMENT', '维护附件', '上传或补充权限范围内的业务附件。', 'HIGH', 1, 910),
  ('todo.read', 'TODO', '查看待办', '查看当前角色和数据范围内的业务待办。', 'LOW', 1, 1000),
  ('todo.transition', 'TODO', '处理待办', '领取、提交、复核、驳回或完成业务待办。', 'MEDIUM', 1, 1010);

delete from role_permission
where upper(role_code) in (
  'BOSS', 'ADMIN', 'OWNER', 'FINANCE', 'WAREHOUSE', 'STORE_MANAGER',
  'OPERATIONS', 'OPS', 'SUPERVISOR', 'EMPLOYEE'
);

insert into role_permission(tenant_id, role_code, permission_code, created_at)
select tenant.id, template.role_code, template.permission_code, current_timestamp
from tenant
cross join (values
  ('FINANCE', 'assistant.use'),
  ('FINANCE', 'store.read'),
  ('FINANCE', 'employee.read'),
  ('FINANCE', 'finance.profit.read'),
  ('FINANCE', 'finance.profit.write'),
  ('FINANCE', 'finance.export'),
  ('FINANCE', 'expense.create'),
  ('FINANCE', 'expense.read'),
  ('FINANCE', 'expense.review'),
  ('FINANCE', 'salary.read'),
  ('FINANCE', 'salary.edit'),
  ('FINANCE', 'salary.review'),
  ('FINANCE', 'salary.pay'),
  ('FINANCE', 'inventory.read'),
  ('FINANCE', 'attachment.read'),
  ('FINANCE', 'attachment.write'),
  ('FINANCE', 'todo.read'),
  ('FINANCE', 'todo.transition'),
  ('WAREHOUSE', 'assistant.use'),
  ('WAREHOUSE', 'store.read'),
  ('WAREHOUSE', 'warehouse.central.read'),
  ('WAREHOUSE', 'warehouse.central.manage'),
  ('WAREHOUSE', 'warehouse.store.read'),
  ('WAREHOUSE', 'warehouse.requisition.review'),
  ('WAREHOUSE', 'attachment.read'),
  ('WAREHOUSE', 'attachment.write'),
  ('WAREHOUSE', 'todo.read'),
  ('WAREHOUSE', 'todo.transition'),
  ('WAREHOUSE', 'exam.learn'),
  ('STORE_MANAGER', 'assistant.use'),
  ('STORE_MANAGER', 'store.read'),
  ('STORE_MANAGER', 'store.manage'),
  ('STORE_MANAGER', 'employee.read'),
  ('STORE_MANAGER', 'employee.manage'),
  ('STORE_MANAGER', 'finance.profit.read'),
  ('STORE_MANAGER', 'finance.profit.write'),
  ('STORE_MANAGER', 'expense.create'),
  ('STORE_MANAGER', 'expense.read'),
  ('STORE_MANAGER', 'salary.read'),
  ('STORE_MANAGER', 'warehouse.store.read'),
  ('STORE_MANAGER', 'warehouse.requisition.create'),
  ('STORE_MANAGER', 'warehouse.requisition.receive'),
  ('STORE_MANAGER', 'inventory.read'),
  ('STORE_MANAGER', 'inventory.manage'),
  ('STORE_MANAGER', 'inspection.read'),
  ('STORE_MANAGER', 'exam.learn'),
  ('STORE_MANAGER', 'exam.report'),
  ('STORE_MANAGER', 'attachment.read'),
  ('STORE_MANAGER', 'attachment.write'),
  ('STORE_MANAGER', 'todo.read'),
  ('STORE_MANAGER', 'todo.transition'),
  ('OPERATIONS', 'operations.dashboard.read'),
  ('OPERATIONS', 'assistant.use'),
  ('OPERATIONS', 'store.read'),
  ('OPERATIONS', 'store.manage'),
  ('OPERATIONS', 'employee.read'),
  ('OPERATIONS', 'warehouse.store.read'),
  ('OPERATIONS', 'inventory.read'),
  ('OPERATIONS', 'inventory.manage'),
  ('OPERATIONS', 'inventory.review'),
  ('OPERATIONS', 'inspection.read'),
  ('OPERATIONS', 'inspection.manage'),
  ('OPERATIONS', 'exam.learn'),
  ('OPERATIONS', 'exam.manage'),
  ('OPERATIONS', 'exam.report'),
  ('OPERATIONS', 'platform.read'),
  ('OPERATIONS', 'platform.manage'),
  ('OPERATIONS', 'attachment.read'),
  ('OPERATIONS', 'attachment.write'),
  ('OPERATIONS', 'todo.read'),
  ('OPERATIONS', 'todo.transition'),
  ('EMPLOYEE', 'exam.learn')
) template(role_code, permission_code);

insert into user_permission_override(
  tenant_id, user_id, permission_code, effect, created_by, created_at
)
select auth_user.tenant_id,
       auth_user.id,
       permission.permission_code,
       'ALLOW',
       null,
       current_timestamp
from auth_user
cross join (values ('inspection.read'), ('inspection.manage')) permission(permission_code)
where upper(auth_user.role) = 'SUPERVISOR';

update auth_user
set store_id = (
  select min(scope.store_id)
  from user_store_scope scope
  where scope.tenant_id = auth_user.tenant_id
    and scope.user_id = auth_user.id
)
where upper(role) = 'STORE_MANAGER'
  and (store_id is null or trim(store_id) = '')
  and exists (
    select 1
    from user_store_scope scope
    where scope.tenant_id = auth_user.tenant_id
      and scope.user_id = auth_user.id
  );

drop table if exists v37_effective_store_scope;

create local temporary table v37_effective_store_scope as
select scope_entry.tenant_id,
       scope_entry.user_id,
       json_arrayagg(scope_entry.store_id) as scope_value_json
from (
  select tenant_id, user_id, store_id
  from user_store_scope
  where store_id is not null and trim(store_id) <> ''
  union
  select tenant_id, id as user_id, store_id
  from auth_user
  where store_id is not null and trim(store_id) <> ''
) scope_entry
group by scope_entry.tenant_id, scope_entry.user_id;

insert into user_data_scope(
  tenant_id, user_id, domain_code, scope_type, scope_value_json, created_by, created_at
)
select auth_user.tenant_id,
       auth_user.id,
       domain.domain_code,
       case when effective_scope.scope_value_json is null then 'ALL' else 'STORE_LIST' end,
       effective_scope.scope_value_json,
       null,
       current_timestamp
from auth_user
cross join (values ('STORE'), ('FINANCE'), ('SALARY'), ('WAREHOUSE')) domain(domain_code)
left join v37_effective_store_scope effective_scope
  on effective_scope.tenant_id = auth_user.tenant_id
 and effective_scope.user_id = auth_user.id
where upper(auth_user.role) = 'FINANCE';

insert into user_data_scope(
  tenant_id, user_id, domain_code, scope_type, scope_value_json, created_by, created_at
)
select auth_user.tenant_id, auth_user.id, 'WAREHOUSE', 'CENTRAL_WAREHOUSE', null, null, current_timestamp
from auth_user
where upper(auth_user.role) = 'WAREHOUSE';

insert into user_data_scope(
  tenant_id, user_id, domain_code, scope_type, scope_value_json, created_by, created_at
)
select auth_user.tenant_id,
       auth_user.id,
       domain.domain_code,
       case
         when auth_user.store_id is not null and trim(auth_user.store_id) <> '' then 'OWN_STORE'
         else 'NONE'
       end,
       null,
       null,
       current_timestamp
from auth_user
cross join (values
  ('STORE'), ('FINANCE'), ('SALARY'), ('WAREHOUSE'), ('INSPECTION'), ('EXAM')
) domain(domain_code)
left join v37_effective_store_scope effective_scope
  on effective_scope.tenant_id = auth_user.tenant_id
 and effective_scope.user_id = auth_user.id
where upper(auth_user.role) = 'STORE_MANAGER';

insert into user_data_scope(
  tenant_id, user_id, domain_code, scope_type, scope_value_json, created_by, created_at
)
select auth_user.tenant_id,
       auth_user.id,
       domain.domain_code,
       case when effective_scope.scope_value_json is null then 'NONE' else 'STORE_LIST' end,
       effective_scope.scope_value_json,
       null,
       current_timestamp
from auth_user
cross join (values
  ('STORE'), ('WAREHOUSE'), ('INSPECTION'), ('EXAM'), ('PLATFORM')
) domain(domain_code)
left join v37_effective_store_scope effective_scope
  on effective_scope.tenant_id = auth_user.tenant_id
 and effective_scope.user_id = auth_user.id
where upper(auth_user.role) in ('OPERATIONS', 'OPS', 'SUPERVISOR');

insert into user_data_scope(
  tenant_id, user_id, domain_code, scope_type, scope_value_json, created_by, created_at
)
select auth_user.tenant_id, auth_user.id, 'EXAM', 'SELF', null, null, current_timestamp
from auth_user
where upper(auth_user.role) = 'EMPLOYEE';

drop table if exists v37_effective_store_scope;

update business_todo
set assignee_role = case
      when upper(assignee_role) in ('SUPERVISOR', 'OPS') then 'OPERATIONS'
      else assignee_role
    end,
    review_role = case
      when upper(review_role) in ('SUPERVISOR', 'OPS') then 'OPERATIONS'
      else review_role
    end,
    updated_at = current_timestamp
where status not in ('COMPLETED', 'REJECTED')
  and (
    upper(assignee_role) in ('SUPERVISOR', 'OPS')
    or upper(review_role) in ('SUPERVISOR', 'OPS')
  );

update todo_escalation
set source_role = 'OPERATIONS'
where status <> 'RESOLVED'
  and upper(source_role) in ('SUPERVISOR', 'OPS');

update auth_user
set role = case
      when upper(role) in ('ADMIN', 'OWNER') then 'BOSS'
      when upper(role) in ('SUPERVISOR', 'OPS') then 'OPERATIONS'
      else upper(role)
    end,
    store_id = case
      when upper(role) in ('ADMIN', 'OWNER') then null
      else store_id
    end
where upper(role) in ('ADMIN', 'OWNER', 'SUPERVISOR', 'OPS');

update auth_user set permission_version = permission_version + 1;
delete from auth_token;
