-- 与 MySQL V47 语义一致：仅保存审批知识、脱敏问题和处理结论，不保存完整原始会话。

create table employee_assistant_knowledge (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  category varchar(64) not null,
  title varchar(160) not null,
  keywords varchar(1000) not null,
  standard_answer clob not null,
  status varchar(16) not null,
  current_version int not null default 0,
  created_by bigint not null,
  updated_by bigint not null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  constraint uk_employee_assistant_knowledge_title unique (tenant_id, title)
);
create index idx_employee_assistant_knowledge_lookup
  on employee_assistant_knowledge(tenant_id, status, category);

create table employee_assistant_knowledge_version (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  knowledge_id bigint not null,
  version_no int not null,
  category varchar(64) not null,
  title varchar(160) not null,
  keywords varchar(1000) not null,
  standard_answer clob not null,
  publish_action varchar(16) not null,
  published_by bigint not null,
  published_at timestamp not null default current_timestamp,
  constraint uk_employee_assistant_knowledge_version unique (tenant_id, knowledge_id, version_no)
);
create index idx_employee_assistant_knowledge_version_lookup
  on employee_assistant_knowledge_version(tenant_id, knowledge_id, published_at);

create table employee_assistant_handoff (
  id varchar(64) not null primary key,
  tenant_id bigint not null,
  store_id varchar(64),
  question_redacted varchar(1200) not null,
  category varchar(64) not null,
  status varchar(16) not null,
  requested_by bigint not null,
  handled_by bigint,
  resolution varchar(2000),
  created_at timestamp not null default current_timestamp,
  claimed_at timestamp,
  responded_at timestamp,
  closed_at timestamp,
  expires_at timestamp not null,
  updated_at timestamp not null default current_timestamp
);
create index idx_employee_assistant_handoff_queue
  on employee_assistant_handoff(tenant_id, status, expires_at, created_at);
create index idx_employee_assistant_handoff_store
  on employee_assistant_handoff(tenant_id, store_id, status);
create index idx_employee_assistant_handoff_requester
  on employee_assistant_handoff(tenant_id, requested_by, created_at);

create table employee_assistant_feedback (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  answer_source varchar(32) not null,
  knowledge_id bigint,
  knowledge_version int,
  helpful boolean not null,
  reason_code varchar(64),
  created_by bigint not null,
  created_at timestamp not null default current_timestamp
);
create index idx_employee_assistant_feedback_knowledge
  on employee_assistant_feedback(tenant_id, knowledge_id, knowledge_version);
create index idx_employee_assistant_feedback_creator
  on employee_assistant_feedback(tenant_id, created_by, created_at);

insert into permission_catalog(
  permission_code, module_code, permission_name, description, risk_level, enabled, sort_order
)
select 'employee_assistant.knowledge_manage', 'EMPLOYEE_ASSISTANT', '管理员工助手知识库',
       '维护、发布和回滚已审批的员工服务标准话术，仅限老板。', 'HIGH', 1, 77
where not exists (select 1 from permission_catalog where permission_code = 'employee_assistant.knowledge_manage');

insert into permission_catalog(
  permission_code, module_code, permission_name, description, risk_level, enabled, sort_order
)
select 'employee_assistant.handoff_manage', 'EMPLOYEE_ASSISTANT', '处理员工助手人工事项',
       '领取、回复和关闭权限范围内的员工助手人工转接事项。', 'HIGH', 1, 78
where not exists (select 1 from permission_catalog where permission_code = 'employee_assistant.handoff_manage');

insert into role_permission(tenant_id, role_code, permission_code, created_at)
select tenant.id, 'OPERATIONS', 'employee_assistant.handoff_manage', current_timestamp
from tenant
where not exists (
  select 1 from role_permission existing
  where existing.tenant_id = tenant.id
    and existing.role_code = 'OPERATIONS'
    and existing.permission_code = 'employee_assistant.handoff_manage'
);

update auth_user
set permission_version = permission_version + 1,
    updated_at = current_timestamp
where upper(role) in ('BOSS', 'OPERATIONS', 'OPS', 'SUPERVISOR');

delete from auth_token token
where exists (
  select 1 from auth_user account
  where account.tenant_id = token.tenant_id
    and account.id = token.user_id
    and upper(account.role) in ('BOSS', 'OPERATIONS', 'OPS', 'SUPERVISOR')
);
