-- H2 equivalent of V52__training_course_videos.sql.

create table training_video (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  video_code varchar(120) not null,
  attachment_id bigint not null,
  course_id bigint null,
  title varchar(160) not null,
  category varchar(120) null,
  description varchar(500) null,
  duration_seconds decimal(10,2) null,
  enabled tinyint not null default 1,
  sort_order int not null default 0,
  created_by bigint not null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp null default null,
  constraint uk_training_video_code unique (tenant_id, video_code),
  constraint uk_training_video_attachment unique (tenant_id, attachment_id),
  constraint fk_training_video_tenant foreign key (tenant_id) references tenant(id),
  constraint fk_training_video_attachment foreign key (attachment_id) references warehouse_attachment(id),
  constraint fk_training_video_course foreign key (course_id) references training_course(id),
  constraint fk_training_video_creator foreign key (created_by) references auth_user(id)
);

create index idx_training_video_course on training_video(tenant_id, course_id, sort_order);
create index idx_training_video_enabled on training_video(tenant_id, enabled, sort_order);

create table training_video_progress (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  video_id bigint not null,
  user_id bigint not null,
  user_name varchar(120) not null,
  store_id varchar(64) null,
  watched_seconds decimal(10,2) not null default 0,
  duration_seconds decimal(10,2) null,
  progress_percent decimal(5,2) not null default 0,
  last_position decimal(10,2) not null default 0,
  completed tinyint not null default 0,
  completed_at timestamp null,
  last_reported_at timestamp null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp null default null,
  constraint uk_training_video_progress unique (tenant_id, video_id, user_id),
  constraint chk_training_video_progress_watched check (watched_seconds >= 0),
  constraint chk_training_video_progress_percent check (progress_percent >= 0 and progress_percent <= 100),
  constraint fk_training_video_progress_tenant foreign key (tenant_id) references tenant(id),
  constraint fk_training_video_progress_video foreign key (video_id) references training_video(id),
  constraint fk_training_video_progress_user foreign key (user_id) references auth_user(id)
);

create index idx_training_video_progress_user
  on training_video_progress(tenant_id, user_id, last_reported_at);
