-- H2 equivalent of V63__daily_loss_reimbursement_daily_refactor.sql.

create table if not exists loss_item_config (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1,
  item_code varchar(120) not null,
  item_name varchar(160) not null,
  category varchar(80) not null,
  unit varchar(40) not null,
  unit_price decimal(18,4) not null,
  source_sheet varchar(120) not null,
  active boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp null,
  constraint uk_loss_item_config_code unique (tenant_id, item_code),
  constraint chk_loss_item_config_price check (unit_price >= 0)
);

create index if not exists idx_loss_item_config_active
  on loss_item_config(tenant_id, active, source_sheet, item_code);

create table if not exists daily_loss_report (
  id varchar(120) not null primary key,
  tenant_id bigint not null,
  store_id varchar(64) not null,
  loss_date date not null,
  status varchar(32) not null default 'DRAFT',
  submitted_by bigint null,
  submitted_at timestamp null,
  reviewed_by bigint null,
  reviewed_at timestamp null,
  review_note varchar(500) null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp null,
  constraint uk_daily_loss_report_store_day unique (tenant_id, store_id, loss_date),
  constraint chk_daily_loss_report_status check (status in ('DRAFT', 'SUBMITTED', 'REVIEWED', 'REJECTED'))
);

create index if not exists idx_daily_loss_report_month
  on daily_loss_report(tenant_id, store_id, loss_date, status);
create index if not exists idx_daily_loss_report_status
  on daily_loss_report(tenant_id, status, submitted_at);

alter table daily_loss_record add column if not exists report_id varchar(120);
alter table daily_loss_record add column if not exists item_config_id bigint;
alter table daily_loss_record alter column item_id drop not null;
create index if not exists idx_daily_loss_report
  on daily_loss_record(tenant_id, report_id, id);

alter table expense_claim add column if not exists expense_date date;
create index if not exists idx_expense_tenant_store_date
  on expense_claim(tenant_id, store_id, expense_date, status);

merge into permission_catalog(
  permission_code, module_code, permission_name, description, risk_level, enabled, sort_order
) key(permission_code) values
  ('daily_loss.read', 'DAILY_LOSS', '查看每日报损', '店长查看本店，督导和老板查看授权门店，财务只读查看。', 'MEDIUM', 1, 615),
  ('daily_loss.create', 'DAILY_LOSS', '提交每日报损', '店长为所属门店提交多品类每日报损。', 'MEDIUM', 1, 616),
  ('daily_loss.review', 'DAILY_LOSS', '复核每日报损', '督导复核授权门店每日报损并可导出当月照片包。', 'HIGH', 1, 617);

delete from role_permission
where permission_code in ('daily_loss.read', 'daily_loss.create', 'daily_loss.review')
  and upper(role_code) in ('OPERATIONS', 'WAREHOUSE', 'FINANCE', 'SUPERVISOR', 'STORE_MANAGER');

insert into role_permission(tenant_id, role_code, permission_code, created_at)
select tenant.id, template.role_code, template.permission_code, current_timestamp
from tenant
join (
  select 'STORE_MANAGER' as role_code, 'daily_loss.read' as permission_code
  union all select 'STORE_MANAGER', 'daily_loss.create'
  union all select 'SUPERVISOR', 'daily_loss.read'
  union all select 'SUPERVISOR', 'daily_loss.review'
  union all select 'FINANCE', 'daily_loss.read'
) template on 1 = 1
where not exists (
  select 1 from role_permission existing
  where existing.tenant_id = tenant.id
    and existing.role_code = template.role_code
    and existing.permission_code = template.permission_code
);

update auth_user
set permission_version = permission_version + 1,
    updated_at = current_timestamp
where upper(role) in ('OPERATIONS', 'WAREHOUSE', 'FINANCE', 'SUPERVISOR', 'STORE_MANAGER');

delete from auth_token
where user_id in (
  select id from auth_user
  where upper(role) in ('OPERATIONS', 'WAREHOUSE', 'FINANCE', 'SUPERVISOR', 'STORE_MANAGER')
);
