-- H2 verification equivalent of MySQL V75.

create table knowledge_base_document (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  title varchar(200) not null,
  category varchar(64) not null,
  original_file_name varchar(255) not null,
  content_type varchar(160) not null,
  file_size bigint not null,
  file_sha256 char(64) not null,
  source_content blob not null,
  visibility varchar(16) not null,
  status varchar(16) not null,
  parsed_char_count int not null default 0,
  chunk_count int not null default 0,
  created_by bigint not null,
  published_by bigint,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  published_at timestamp,
  constraint uk_knowledge_base_document_file unique (tenant_id, file_sha256)
);
create index idx_knowledge_base_document_list
  on knowledge_base_document(tenant_id, status, updated_at);
create index idx_knowledge_base_document_creator
  on knowledge_base_document(tenant_id, created_by, created_at);

create table knowledge_base_document_role_scope (
  document_id bigint not null,
  role_code varchar(32) not null,
  primary key (document_id, role_code),
  constraint fk_knowledge_base_document_role_scope_document
    foreign key (document_id) references knowledge_base_document(id) on delete cascade
);

create table knowledge_base_document_store_scope (
  document_id bigint not null,
  store_id varchar(64) not null,
  primary key (document_id, store_id),
  constraint fk_knowledge_base_document_store_scope_document
    foreign key (document_id) references knowledge_base_document(id) on delete cascade
);
create index idx_knowledge_base_document_store_scope_store
  on knowledge_base_document_store_scope(store_id, document_id);

create table knowledge_base_chunk (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  document_id bigint not null,
  chunk_no int not null,
  source_locator varchar(255) not null,
  content clob not null,
  content_hash char(64) not null,
  embedding_model varchar(64) not null,
  embedding_dimensions smallint not null,
  embedding blob not null,
  created_at timestamp not null default current_timestamp,
  constraint uk_knowledge_base_chunk_position unique (document_id, chunk_no),
  constraint fk_knowledge_base_chunk_document
    foreign key (document_id) references knowledge_base_document(id) on delete cascade
);
create index idx_knowledge_base_chunk_document
  on knowledge_base_chunk(tenant_id, document_id);

insert into permission_catalog(
  permission_code, module_code, permission_name, description, risk_level, enabled, sort_order
)
select 'knowledge_base.search', 'KNOWLEDGE_BASE', '检索知识库', '检索已发布且在本人角色、门店范围内的内部资料。', 'MEDIUM', 1, 79
where not exists (select 1 from permission_catalog where permission_code = 'knowledge_base.search');

insert into permission_catalog(
  permission_code, module_code, permission_name, description, risk_level, enabled, sort_order
)
select 'knowledge_base.manage', 'KNOWLEDGE_BASE', '管理知识库', '上传、发布和下架受控的 Word、Excel、CSV 与文本知识资料，仅限老板和督导。', 'HIGH', 1, 80
where not exists (select 1 from permission_catalog where permission_code = 'knowledge_base.manage');

insert into role_permission(tenant_id, role_code, permission_code, created_at)
select tenant.id, 'BOSS', 'knowledge_base.search', current_timestamp from tenant
where not exists (select 1 from role_permission existing where existing.tenant_id = tenant.id and existing.role_code = 'BOSS' and existing.permission_code = 'knowledge_base.search');
insert into role_permission(tenant_id, role_code, permission_code, created_at)
select tenant.id, 'FINANCE', 'knowledge_base.search', current_timestamp from tenant
where not exists (select 1 from role_permission existing where existing.tenant_id = tenant.id and existing.role_code = 'FINANCE' and existing.permission_code = 'knowledge_base.search');
insert into role_permission(tenant_id, role_code, permission_code, created_at)
select tenant.id, 'SUPERVISOR', 'knowledge_base.search', current_timestamp from tenant
where not exists (select 1 from role_permission existing where existing.tenant_id = tenant.id and existing.role_code = 'SUPERVISOR' and existing.permission_code = 'knowledge_base.search');
insert into role_permission(tenant_id, role_code, permission_code, created_at)
select tenant.id, 'WAREHOUSE', 'knowledge_base.search', current_timestamp from tenant
where not exists (select 1 from role_permission existing where existing.tenant_id = tenant.id and existing.role_code = 'WAREHOUSE' and existing.permission_code = 'knowledge_base.search');
insert into role_permission(tenant_id, role_code, permission_code, created_at)
select tenant.id, 'STORE_MANAGER', 'knowledge_base.search', current_timestamp from tenant
where not exists (select 1 from role_permission existing where existing.tenant_id = tenant.id and existing.role_code = 'STORE_MANAGER' and existing.permission_code = 'knowledge_base.search');
insert into role_permission(tenant_id, role_code, permission_code, created_at)
select tenant.id, 'EMPLOYEE', 'knowledge_base.search', current_timestamp from tenant
where not exists (select 1 from role_permission existing where existing.tenant_id = tenant.id and existing.role_code = 'EMPLOYEE' and existing.permission_code = 'knowledge_base.search');

insert into role_permission(tenant_id, role_code, permission_code, created_at)
select tenant.id, 'BOSS', 'knowledge_base.manage', current_timestamp from tenant
where not exists (select 1 from role_permission existing where existing.tenant_id = tenant.id and existing.role_code = 'BOSS' and existing.permission_code = 'knowledge_base.manage');
insert into role_permission(tenant_id, role_code, permission_code, created_at)
select tenant.id, 'SUPERVISOR', 'knowledge_base.manage', current_timestamp from tenant
where not exists (select 1 from role_permission existing where existing.tenant_id = tenant.id and existing.role_code = 'SUPERVISOR' and existing.permission_code = 'knowledge_base.manage');

update auth_user
set permission_version = permission_version + 1,
    updated_at = current_timestamp
where upper(role) in ('BOSS', 'FINANCE', 'SUPERVISOR', 'WAREHOUSE', 'STORE_MANAGER', 'EMPLOYEE');

delete from auth_token
where user_id in (
  select id from auth_user
  where upper(role) in ('BOSS', 'FINANCE', 'SUPERVISOR', 'WAREHOUSE', 'STORE_MANAGER', 'EMPLOYEE')
);
