-- H2 V76 verifies the production QMAI credential shape introduced by MySQL V78.
drop table if exists qmai_platform_config;
create table qmai_platform_config (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  brand varchar(40) not null default 'ruguo',
  open_id clob not null default '',
  grant_code clob not null default '',
  open_key clob not null default '',
  base_url varchar(300) not null default '',
  version varchar(40) not null default '',
  shops clob null,
  console_account clob not null default '',
  console_password clob not null default '',
  console_token clob null,
  updated_by_user_id bigint null,
  updated_by_name varchar(120) null,
  updated_at timestamp not null default current_timestamp,
  created_at timestamp not null default current_timestamp,
  constraint uk_qmai_config_tenant_brand unique (tenant_id, brand),
  constraint fk_qmai_config_tenant foreign key (tenant_id) references tenant(id)
);
