create table qmai_recipe_definition (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null,
  brand_code varchar(40) not null,
  product_name varchar(300) not null,
  active tinyint not null default 1,
  version_no int not null default 1,
  updated_by_user_id bigint null,
  updated_by_name varchar(120) null,
  updated_at timestamp not null default current_timestamp,
  created_at timestamp not null default current_timestamp,
  constraint uk_qmai_recipe_definition unique (tenant_id, brand_code, product_name),
  constraint fk_qmai_recipe_definition_tenant foreign key (tenant_id) references tenant(id)
);

create table qmai_recipe_ingredient (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null,
  material_name varchar(300) not null,
  fruit_name varchar(160) not null,
  grams_per_cup decimal(18,3) not null,
  conversion_kind varchar(16) not null,
  conversion_factor decimal(18,6) null,
  sort_order int not null default 0,
  constraint chk_qmai_recipe_kind check (conversion_kind in ('FLESH', 'JUICE', 'ONE')),
  constraint fk_qmai_recipe_ingredient_recipe foreign key (recipe_id) references qmai_recipe_definition(id) on delete cascade
);
