create table if not exists warehouse_return_order (
  id varchar(120) not null primary key,
  tenant_id bigint not null,
  return_no varchar(120) not null,
  return_store_id varchar(64) not null,
  return_store_name varchar(160) not null,
  receive_department varchar(120) not null default '采购',
  status varchar(40) not null default 'CHECKED',
  total_amount decimal(14,2) not null default 0,
  handled_by varchar(500) null,
  created_by varchar(120) null,
  updated_by varchar(120) null,
  reviewed_by varchar(120) null,
  checked_by varchar(120) null,
  note text null,
  return_date date not null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp null default null,
  unique key uk_return_order_tenant_no (tenant_id, return_no),
  index idx_return_order_tenant_store (tenant_id, return_store_id, return_date),
  index idx_return_order_tenant_status (tenant_id, status, return_date),
  constraint fk_return_order_tenant foreign key (tenant_id) references tenant(id),
  constraint fk_return_order_store foreign key (return_store_id) references store_branch(id)
);

create table if not exists warehouse_return_order_line (
  id bigint not null auto_increment primary key,
  tenant_id bigint not null,
  return_order_id varchar(120) not null,
  item_id bigint not null,
  item_name varchar(160) not null,
  spec varchar(160) null,
  quantity decimal(14,2) not null default 0,
  unit varchar(40) not null default '件',
  unit_price decimal(14,2) not null default 0,
  return_price decimal(14,2) not null default 0,
  amount decimal(14,2) not null default 0,
  note text null,
  index idx_return_line_order (tenant_id, return_order_id),
  index idx_return_line_item (tenant_id, item_id),
  constraint fk_return_line_tenant foreign key (tenant_id) references tenant(id),
  constraint fk_return_line_order foreign key (return_order_id) references warehouse_return_order(id),
  constraint fk_return_line_item foreign key (item_id) references warehouse_item(id)
);
