<script setup lang="ts">
import { computed, ref } from 'vue'
import { onPullDownRefresh, onShow } from '@dcloudio/uni-app'
import { completeMobileFinanceCheck, getMobileFinanceWorkbench } from '@/api/business'
import { useContextStore, useSessionStore } from '@/stores'
import type { FinanceWorkbench, RoleTodoItem } from '@/types/business'
import { isBoss } from '@/permissions'

const session=useSessionStore(),context=useContextStore(),workbench=ref<FinanceWorkbench|null>(null),loading=ref(false),message=ref(''),acting=ref('')
const month=ref(new Date().toISOString().slice(0,7)),storeId=ref(''),tab=ref<'action'|'profit'|'expense'|'salary'|'data'>('action')
const canRead=computed(()=> (isBoss(session.user) || session.user?.role==='FINANCE') && session.hasPermission('finance.profit.read'))
const storeOptions=computed(()=>[{id:'',name:'全部授权门店'},...context.stores]),storeIndex=computed(()=>Math.max(0,storeOptions.value.findIndex(item=>item.id===storeId.value)))
const tabs=[{key:'action',label:'待处理'},{key:'profit',label:'利润风险'},{key:'expense',label:'报销'},{key:'salary',label:'工资核对'},{key:'data',label:'数据核对'}] as const
onShow(async()=>{if(!context.stores.length&&session.user)await context.load(session.user);await refresh()});onPullDownRefresh(async()=>{await refresh();uni.stopPullDownRefresh()})
async function refresh(){if(!canRead.value||loading.value)return;loading.value=true;message.value='';try{workbench.value=await getMobileFinanceWorkbench({month:month.value,storeId:storeId.value||undefined});month.value=workbench.value.month||month.value}catch(cause){message.value=friendlyError(cause)}finally{loading.value=false}}
async function chooseMonth(event:{detail:{value:string}}){month.value=String(event.detail.value||month.value).slice(0,7);await refresh()}
async function chooseStore(event:{detail:{value:string|number}}){storeId.value=storeOptions.value[Number(event.detail.value)]?.id||'';await refresh()}
function openTodo(item:RoleTodoItem){if(item.id.startsWith('salary-check-')){const id=item.sourceRecordId||item.id.slice('salary-check-'.length);uni.navigateTo({url:`/pkg-finance/salary-detail/index?id=${encodeURIComponent(id)}`});return}if(item.id.startsWith('finance-data-')||item.sourceModule==='PROFIT'){openProfit(item.storeId,item.action?.params?.month as string|undefined);return}if(item.id.startsWith('expense-')||item.sourceModule==='EXPENSE'){uni.navigateTo({url:'/pkg-finance/expenses/index'});return}uni.navigateTo({url:`/pages/todo-detail/index?id=${encodeURIComponent(item.id)}`})}
function openProfit(targetStoreId?:string,targetMonth?:string){const query:string[]=[];if(targetStoreId)query.push(`storeId=${encodeURIComponent(targetStoreId)}`);if(targetMonth)query.push(`month=${encodeURIComponent(targetMonth)}`);uni.navigateTo({url:`/pkg-finance/profit/index${query.length?`?${query.join('&')}`:''}`})}
function openExpense(){uni.navigateTo({url:'/pkg-finance/expenses/index'})}function openSalary(id:string){uni.navigateTo({url:`/pkg-finance/salary-detail/index?id=${encodeURIComponent(id)}`})}
async function complete(item:RoleTodoItem){if(!['salary-check-','finance-data-'].some(prefix=>item.id.startsWith(prefix))||acting.value)return;const note=await askNote();if(!note)return;acting.value=item.id;try{await completeMobileFinanceCheck(item.id,note);message.value='核对事项已完成。';await refresh()}catch(cause){message.value=friendlyError(cause)}finally{acting.value=''}}
function askNote(){return new Promise<string>(resolve=>uni.showModal({title:'填写核对结论',editable:true,placeholderText:'请输入核对说明',success:result=>resolve(result.confirm?String(result.content||'').trim():''),fail:()=>resolve('')}))}
function money(value:unknown){return`¥${Number(value||0).toFixed(2)}`}function statusText(status?:string){return({DRAFT:'草稿',SUBMITTED:'待审核',APPROVED:'已审核',REJECTED:'已驳回',PAID:'已发放',LOCKED:'已锁定',PENDING:'待处理',DONE:'已完成'}as Record<string,string>)[String(status||'')]||status||'—'}
function friendlyError(cause:unknown){const status=Number((cause as{status?:number})?.status||0);return status===403?'当前账号无权查看该财务范围。':status===401?'登录已过期，请重新登录。':'财务工作台暂时无法加载。'}
</script>
<template><view class="page"><view class="head"><view><text class="eyebrow">经营财务</text><text class="title">财务工作台</text></view><button :loading="loading" :disabled="loading||!canRead" @click="refresh">刷新</button></view><view class="filters"><picker mode="date" fields="month" :value="month" @change="chooseMonth"><view class="picker">{{month}}</view></picker><picker :range="storeOptions" range-key="name" :value="storeIndex" @change="chooseStore"><view class="picker">{{storeOptions[storeIndex]?.name}}</view></picker></view><view v-if="message" class="notice">{{message}}</view><template v-if="workbench"><view class="focus"><text class="focus-copy">{{workbench.todayFocus.summary}}</text><view class="metrics"><view><text>{{workbench.todayFocus.pendingExpenseCount}}</text><text>待审报销</text></view><view><text>{{workbench.todayFocus.profitRiskStoreCount}}</text><text>风险门店</text></view><view><text>{{workbench.todayFocus.salaryCheckCount}}</text><text>工资核对</text></view><view><text>{{workbench.todayFocus.escalatedToBossCount}}</text><text>已升级</text></view></view></view><scroll-view scroll-x class="tab-scroll"><view class="tabs"><button v-for="item in tabs" :key="item.key" :class="{active:tab===item.key}" @click="tab=item.key">{{item.label}}</button></view></scroll-view>
<template v-if="tab==='action'"><view v-if="!workbench.needMyAction.length" class="state">暂无待处理事项</view><view v-for="item in workbench.needMyAction" :key="item.id" class="card"><view class="row"><text class="name">{{item.title}}</text><text class="priority">P{{item.priority}}</text></view><text class="copy">{{item.summary||'进入业务详情处理'}}</text><view class="actions"><button @click="openTodo(item)">查看详情</button><button v-if="item.id.startsWith('salary-check-')||item.id.startsWith('finance-data-')" :loading="acting===item.id" :disabled="Boolean(acting)" @click="complete(item)">标记已核对</button></view></view></template>
<template v-else-if="tab==='profit'"><view v-if="!workbench.profitRisks.length" class="state">当前范围无利润风险</view><view v-for="item in workbench.profitRisks" :key="item.id" class="card" @click="openProfit(item.storeId,item.month)"><view class="row"><text class="name">{{item.storeName}}</text><text class="negative">{{money(item.net)}}</text></view><text class="copy">{{item.month}} · 利润率 {{Number(item.margin||0).toFixed(1)}}% · {{item.risk||'需核对'}}</text></view></template>
<template v-else-if="tab==='expense'"><view v-if="!workbench.expenseReviews.length" class="state">当前范围无报销记录</view><view v-for="item in workbench.expenseReviews" :key="item.id" class="card" @click="openExpense"><view class="row"><text class="name">{{item.storeName||item.storeId}}</text><text>{{money(item.amount)}}</text></view><text class="copy">{{item.month}} · {{statusText(item.status)}} · {{item.reason||'暂无事由'}}</text></view></template>
<template v-else-if="tab==='salary'"><view v-if="!workbench.salaryChecks.length" class="state">当前范围无工资核对事项</view><view v-for="item in workbench.salaryChecks" :key="item.id" class="card" @click="openSalary(item.id)"><view class="row"><text class="name">{{item.employeeName}}</text><text>{{money(item.gross)}}</text></view><text class="copy">{{item.storeName}} · {{item.month}} · {{item.anomaly||statusText(item.status)}}</text></view></template>
<template v-else><view v-if="!workbench.dataChecks.length" class="state">当前范围无数据核对事项</view><view v-for="item in workbench.dataChecks" :key="item.id" class="card" @click="openProfit(item.storeId,item.month)"><text class="name">{{item.storeName}}</text><text class="copy">{{item.month}} · {{item.issue}}</text></view></template></template></view></template>
<style scoped lang="scss">.page{min-height:100vh;box-sizing:border-box;padding:24rpx;background:#f2f6f5;color:#202124}.head,.row,.actions{display:flex;align-items:center;justify-content:space-between;gap:12rpx}.eyebrow,.title,.focus-copy,.name,.copy{display:block}.eyebrow,.copy{color:#71807d;font-size:23rpx}.title{margin-top:6rpx;font-size:38rpx;font-weight:750}.head button{margin:0;background:#fff;color:#1f5752}.filters{display:grid;grid-template-columns:1fr 1fr;gap:12rpx;margin-top:18rpx}.picker{padding:18rpx;background:#fff;border:1rpx solid #d9e6e3;border-radius:14rpx;text-align:center;font-size:25rpx}.focus,.card,.notice,.state{margin-top:16rpx;padding:24rpx;background:#fff;border:1rpx solid #d9e6e3;border-radius:16rpx}.focus-copy{font-size:25rpx;line-height:1.6}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8rpx;margin-top:16rpx}.metrics view{text-align:center}.metrics text{display:block}.metrics text:first-child{font-size:31rpx;font-weight:750}.metrics text:last-child{color:#71807d;font-size:21rpx}.tab-scroll{margin-top:18rpx;white-space:nowrap}.tabs{display:inline-flex;gap:10rpx}.tabs button{margin:0;background:#fff;color:#59606b;font-size:24rpx}.tabs button.active{background:#27655f;color:#fff}.name{font-size:28rpx;font-weight:700}.copy{margin-top:9rpx;line-height:1.55}.priority{padding:6rpx 10rpx;background:#e6f3f1;color:#1f5752;border-radius:10rpx;font-size:21rpx}.actions{margin-top:14rpx;justify-content:flex-start}.actions button{margin:0;background:#e6f3f1;color:#1f5752;font-size:24rpx}.negative{color:#c94f43;font-weight:700}.notice,.state{text-align:center;color:#71807d}</style>
