<script setup lang="ts">
import { computed,ref } from 'vue';import{onPullDownRefresh,onShow}from'@dcloudio/uni-app';import{getMobileSalaries,reviewMobileSalary}from'@/api/business';import{useContextStore,useSessionStore}from'@/stores';import type{SalaryRecord}from'@/types/business';import{canPerformMobileAction}from'@/permissions'
const session=useSessionStore(),context=useContextStore(),rows=ref<SalaryRecord[]>([]),loading=ref(false),message=ref(''),acting=ref('');const canReview=computed(()=>canPerformMobileAction(session.user,'salary.review')),canPay=computed(()=>canPerformMobileAction(session.user,'salary.pay'))
onShow(async()=>{if(!context.stores.length&&session.user)await context.load(session.user);await refresh()});onPullDownRefresh(async()=>{await refresh();uni.stopPullDownRefresh()})
async function refresh(){loading.value=true;try{rows.value=await getMobileSalaries({storeId:context.currentStoreId||undefined})}catch(e){message.value=e instanceof Error?e.message:'工资加载失败'}finally{loading.value=false}}
async function act(r:SalaryRecord,a:'approve'|'reject'|'mark-paid'){if(a==='mark-paid'?!canPay.value:!canReview.value)return;acting.value=r.id;try{await reviewMobileSalary(r.id,a,a==='reject'?'移动端驳回，请在桌面端查看详情':undefined);await refresh()}catch(e){message.value=e instanceof Error?e.message:'操作失败'}finally{acting.value=''}}
function openDetail(r:SalaryRecord){uni.navigateTo({url:`/pkg-finance/salary-detail/index?id=${encodeURIComponent(r.id)}`})}
function statusText(status?:string){return({DRAFT:'草稿',SUBMITTED:'待审核',APPROVED:'已审核',REJECTED:'已驳回',PAID:'已发放',LOCKED:'已锁定'}as Record<string,string>)[String(status||'')]||status||'—'}
</script><template><view class="page"><view class="head"><text class="title">工资核对</text><button @click="refresh">刷新</button></view><view v-if="message" class="notice">{{message}}</view><view v-if="!rows.length&&!loading" class="empty">暂无工资记录</view><view v-for="r in rows" :key="r.id" class="card"><view class="head"><text class="name">{{r.employeeName}}</text><text>{{statusText(r.status)}}</text></view><text class="money">实发 {{r.netPay===null||r.netPay===undefined?'—':`¥${Number(r.netPay).toFixed(2)}`}}</text><text class="copy">{{r.storeName||r.storeId}} · {{r.month}} · {{r.position||'员工'}}</text><view class="actions"><button @click="openDetail(r)">查看详情</button><button v-if="canReview&&['SUBMITTED','PENDING_REVIEW'].includes(r.status||'')" @click="act(r,'approve')">审核通过</button><button v-if="canReview&&['SUBMITTED','PENDING_REVIEW'].includes(r.status||'')" @click="act(r,'reject')">驳回</button><button v-if="canPay&&r.status==='APPROVED'" @click="act(r,'mark-paid')">标记发放</button></view></view><view class="hint">工资生成和复杂编辑请使用 PC 管理端。</view></view></template>
<style scoped lang="scss">.page{min-height:100vh;padding:24rpx;background:#f2f6f5}.head,.actions{display:flex;align-items:center;justify-content:space-between;gap:12rpx}.title{font-size:40rpx;font-weight:750}.card,.empty,.notice,.hint{margin-top:16rpx;padding:24rpx;background:#fff;border:1rpx solid #d9e6e3;border-radius:16rpx}.name,.money,.copy{display:block}.name{font-size:29rpx;font-weight:700}.money{margin-top:14rpx;font-size:35rpx;font-weight:750}.copy,.hint{margin-top:8rpx;color:#71807d;font-size:24rpx}.actions{margin-top:16rpx;justify-content:flex-start}.actions button{margin:0;background:#e6f3f1;color:#1f5752;font-size:24rpx}.empty{text-align:center;color:#71807d}</style>
